"""Deliverable Bundle Builder.

Builds structured, multi-directory ZIP deliverables from Artifacts and DeliverableManifest.
Generates manifest.json and a professional README.md delivery index in the bundle root.

[INPUT]
- myrm_agent_harness.core.artifacts.manifest (POS: DeliverableManifest, Category mapping)
- myrm_agent_harness.agent.artifacts.vault::ArtifactVault (POS: Vault object reader)
- app.database.models.artifact::Artifact (POS: DB artifact models)

[OUTPUT]
- build_zip_deliverable_bundle: function — Streams organized ZIP archive with manifest & README
- generate_bundle_readme: function — Generates human-readable README.md delivery guide

[POS]
Server Business Layer — Handles deliverable packaging with safety path sanitization and categorization.
"""

from __future__ import annotations

import io
import json
import logging
import os
import re
import zipfile
from pathlib import Path
from typing import Sequence

from myrm_agent_harness.agent.artifacts.vault import ArtifactVault
from myrm_agent_harness.core.artifacts.manifest import (
    CATEGORY_DIRECTORY_MAPPING,
    DeliverableCategory,
    DeliverableItem,
    DeliverableManifest,
    infer_item_category,
)

from app.database.models.artifact import Artifact

logger = logging.getLogger(__name__)

_INVALID_PATH_CHARS_PATTERN = re.compile(r'[<>:"/\\|?*\x00-\x1f]')


def sanitize_path_segment(segment: str) -> str:
    """Sanitize directory or filename segment against traversal and illegal characters."""
    cleaned = re.sub(r"\.\.+", "", segment)
    cleaned = _INVALID_PATH_CHARS_PATTERN.sub("_", cleaned)
    cleaned = re.sub(r"_+", "_", cleaned).strip(" ._")
    return cleaned or "unnamed"


def generate_bundle_readme(manifest: DeliverableManifest) -> str:
    """Generate professional Markdown README for the deliverable bundle."""
    lines: list[str] = [
        f"# {manifest.title}",
        "",
        manifest.description or "Automated deliverable bundle generated by Myrm Intelligent Agent.",
        "",
        "---",
        "",
        "## 📦 Package Summary",
        f"- **Bundle ID**: `{manifest.bundle_id}`",
        f"- **Total Deliverables**: {len(manifest.items)}",
        f"- **Agent ID**: `{manifest.agent_id or 'default'}`",
        "",
        "## 📂 Directory Structure & Deliverable Items",
        "",
    ]

    # Group items by category
    items_by_cat: dict[DeliverableCategory, list[DeliverableItem]] = {}
    for item in manifest.items:
        items_by_cat.setdefault(item.category, []).append(item)

    for cat in DeliverableCategory:
        items = items_by_cat.get(cat, [])
        if not items:
            continue
        folder_name = CATEGORY_DIRECTORY_MAPPING.get(cat, cat.value)
        lines.append(f"### `{folder_name}/` ({cat.value.replace('_', ' ').title()})")
        lines.append("")
        for item in items:
            status_badge = f"[{item.status.value.upper()}]" if item.status else ""
            desc = f" - {item.description}" if item.description else ""
            platform = f" (Platform: {item.platform})" if item.platform else ""
            lines.append(f"- **`{item.filename}`** {status_badge}{platform}{desc}")
            if item.sha256_hash:
                lines.append(f"  - *SHA-256*: `{item.sha256_hash}`")
        lines.append("")

    lines.extend(
        [
            "---",
            "",
            "## 💡 Distribution & Usage Guide",
            "1. Review the contents under respective categorized folders.",
            "2. Verify hashes against `manifest.json` for integrity audit.",
            "3. Use appropriate platform materials directly for publication or report handoff.",
        ]
    )
    return "\n".join(lines)


def build_zip_deliverable_bundle(
    artifacts: Sequence[Artifact],
    vault: ArtifactVault,
    manifest: DeliverableManifest | None = None,
    workspace_root: str | Path | None = None,
) -> io.BytesIO:
    """Package artifacts into a structured ZIP stream based on manifest or inferred categorization."""
    buf = io.BytesIO()

    # If no explicit manifest provided, build one from artifacts
    if manifest is None:
        items: list[DeliverableItem] = []
        for a in artifacts:
            versions = sorted(a.versions, key=lambda v: v.created_at, reverse=True) if a.versions else []
            latest = versions[0] if versions else None
            cat = infer_item_category(a.name)
            folder = CATEGORY_DIRECTORY_MAPPING.get(cat, "08_misc_deliverables")
            safe_name = sanitize_path_segment(a.name)
            rel_path = f"{folder}/{safe_name}"
            items.append(
                DeliverableItem(
                    id=a.id,
                    filename=a.name,
                    relative_path=rel_path,
                    category=cat,
                    sha256_hash=latest.sha256_hash if latest else "",
                    description=a.description or "",
                )
            )
        manifest = DeliverableManifest(
            title="Deliverables Package",
            description="Organized deliverable assets package",
            items=items,
        )

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        used_entry_paths: set[str] = set()

        # 1. Write artifact files into categorized subfolders (supports dual-source: Vault URI or sandbox disk)
        artifact_map = {a.id: a for a in artifacts}
        ws_path = Path(workspace_root).resolve() if workspace_root else None

        for item in manifest.items:
            artifact = artifact_map.get(item.id)
            latest = None
            if artifact and artifact.versions:
                latest = sorted(artifact.versions, key=lambda v: v.created_at, reverse=True)[0]

            obj_path: Path | None = None
            # 1.1 Check vault uri first
            if latest and latest.vault_uri:
                obj_id = latest.vault_uri.removeprefix("vault://")
                cand_path = vault.get_object_path(obj_id)
                if cand_path.exists():
                    obj_path = cand_path
            elif item.vault_uri:
                obj_id = item.vault_uri.removeprefix("vault://")
                cand_path = vault.get_object_path(obj_id)
                if cand_path.exists():
                    obj_path = cand_path

            # 1.2 Fallback to workspace sandbox physical file if not found in vault
            if (not obj_path or not obj_path.exists()) and ws_path:
                for candidate_rel in (item.relative_path, item.filename, f"artifacts/{item.filename}"):
                    if candidate_rel:
                        cand_disk = (ws_path / candidate_rel).resolve()
                        if cand_disk.is_relative_to(ws_path) and cand_disk.is_file():
                            obj_path = cand_disk
                            break

            if not obj_path or not obj_path.exists():
                logger.warning("Artifact source file not found for %s (%s)", item.id, item.filename)
                continue

            try:
                rel_dir, _, filename = item.relative_path.rpartition("/")
                safe_folder = (
                    sanitize_path_segment(rel_dir)
                    if rel_dir
                    else CATEGORY_DIRECTORY_MAPPING.get(item.category, "08_misc_deliverables")
                )
                safe_filename = sanitize_path_segment(filename or item.filename)
                entry_path = f"{safe_folder}/{safe_filename}" if safe_folder else safe_filename

                # Handle duplicate path collision safely
                if entry_path in used_entry_paths:
                    stem, ext = os.path.splitext(safe_filename)
                    entry_path = f"{safe_folder}/{stem}_{item.id[:6]}{ext}"

                used_entry_paths.add(entry_path)
                zf.write(obj_path, entry_path)
                item.relative_path = entry_path
                if latest and latest.sha256_hash:
                    item.sha256_hash = latest.sha256_hash
            except Exception as exc:
                logger.warning("Failed to write artifact %s to bundle: %s", item.id, exc)

        # 2. Write root manifest.json
        manifest_json_bytes = json.dumps(manifest.model_dump(), indent=2, ensure_ascii=False).encode("utf-8")
        zf.writestr("manifest.json", manifest_json_bytes)

        # 3. Write root README.md delivery index
        readme_content = generate_bundle_readme(manifest).encode("utf-8")
        zf.writestr("README.md", readme_content)

    buf.seek(0)
    return buf
