"""Type definitions for decoupled action watchdog and input firewall suite.

Strict typing applied: No `Any` types allowed.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum


class WatchdogVerdictStatus(StrEnum):
    """Verdict decision made by the decoupled watchdog."""

    APPROVED = "approved"
    BLOCKED = "blocked"
    CIRCUIT_BREAKER_TRIGGERED = "circuit_breaker_triggered"
    NEEDS_CONFIRMATION = "needs_confirmation"


class ThreatSeverity(StrEnum):
    """Severity classification for security violations."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


@dataclass(frozen=True)
class ActionContractSpec:
    """Represents a proposed agent tool invocation and its baseline context."""

    action_id: str
    tool_name: str
    arguments: dict[str, str | int | float | bool | list[str]]
    user_original_intent: str
    caller_role: str = "assistant"
    snapshot_context: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True)
class InvarianceAssertionRule:
    """Explicit semantic invariant rule defined for critical actions."""

    rule_name: str
    target_tool: str
    max_amount_limit: float = 0.0  # If financial tool
    allowed_recipients: tuple[str, ...] = field(default_factory=tuple)  # If messaging/email tool
    prohibited_destinations: tuple[str, ...] = field(default_factory=tuple)
    strict_intent_binding: bool = True


@dataclass
class FirewallSanitizedPayload:
    """Output generated by the inbound multimodal content firewall."""

    source_type: str
    raw_content: str
    sanitized_content: str
    hidden_text_stripped_count: int
    has_markdown_injection: bool
    stripped_tags: list[str] = field(default_factory=list)
    latency_ms: float = 0.0


@dataclass
class WatchdogViolationDetail:
    """Detailed record of an assertion failure or watchdog violation."""

    violation_type: str
    threat_severity: ThreatSeverity
    description: str
    parameter_key: str = ""
    observed_value: str = ""
    expected_constraint: str = ""


@dataclass
class WatchdogInspectionResult:
    """Consolidated inspection outcome from the decoupled watchdog daemon."""

    action_id: str
    verdict: WatchdogVerdictStatus
    confidence_score: float
    violations: list[WatchdogViolationDetail]
    circuit_breaker_active: bool
    latency_ms: float
    rationale: str = ""
