"""Shared constants for chat context compaction."""

from __future__ import annotations

MIN_MESSAGES_TO_COMPACT = 10
MIN_INCREMENTAL_MESSAGES_TO_COMPACT = 2
IDLE_SUMMARY_TARGET_RATIO = 0.20
COMPACTION_FAILURE_COOLDOWN_SECONDS = 300
DEFAULT_TOOL_SCHEMA_TOKEN_RESERVE = 8_000
MAX_TOOL_OVERHEAD_TOKENS = 24_000
TOOL_OVERHEAD_TOKENS_PER_BUILTIN = 400
COMPACT_INACTIVITY_TIMEOUT_S = 90.0
COMPACT_TOTAL_CEILING_S = 600.0
