/**
 * [INPUT]
 * - myrm-agent-desktop 仓内 _ARCH.md 清单、递归源码目录、核心 Rust/TS [INPUT] 路径、行数预算 baseline
 *
 * [OUTPUT]
 * - 分形文档门禁：必检 _ARCH [POS]、递归目录 _ARCH、核心 [INPUT] 头、核心安全文件 git 跟踪状态、Rust 源文件行数预算
 *
 * [POS]
 * 桌面仓分形自文档 CI 守门。对齐 server/frontend check_fractal_docs + check_file_line_budget 纪律。
 */
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const DESKTOP_ROOT = join(import.meta.dir, '..');
const RUST_SRC_ROOT = join(DESKTOP_ROOT, 'src-tauri/src');
const AUTOGENERATED_PERMISSIONS_DIR = join(DESKTOP_ROOT, 'src-tauri/permissions/autogenerated');
const COMMAND_REGISTRY_PATH = join(DESKTOP_ROOT, 'src-tauri/command_registry_macro.in');
const MAX_LINES = 400;
const HEADER_SCAN_LINES = 25;
const INPUT_MARKER = '[INPUT]';
const POS_MARKER = '[POS]';

/** L1 + 非递归扫描根的 _ARCH.md（POS 必检）。递归根下的 _ARCH 由 discoverArchPathsUnderScanRoots 自动发现。 */
const STATIC_ARCH_PATHS = [
  '_ARCH.md',
  'ARCHITECTURE.md',
  'scripts/_ARCH.md',
  'sidecar/_ARCH.md',
  'sidecar/agent-runner/_ARCH.md',
  'src-tauri/frontend-shell/_ARCH.md',
] as const;

const PRUNE_DIR_NAMES = new Set(['target', 'node_modules', '__pycache__', '.git', 'binaries', 'gen']);
const SOURCE_EXTENSIONS = new Set(['.rs', '.ts', '.tsx']);

/** Directories recursively scanned for _ARCH.md (relative to desktop root). */
const RECURSIVE_SCAN_ROOTS = ['src-tauri/src', 'sidecar'] as const;

/** Discover _ARCH.md under recursive scan roots (prevents manual REQUIRED list drift). */
export function discoverArchPathsUnderScanRoots(): string[] {
  const paths = new Set<string>();
  for (const relRoot of RECURSIVE_SCAN_ROOTS) {
    const absRoot = join(DESKTOP_ROOT, relRoot);
    if (!existsSync(absRoot)) {
      continue;
    }
    for (const absDir of collectDirsUnder(absRoot)) {
      const archAbs = join(absDir, '_ARCH.md');
      if (existsSync(archAbs)) {
        paths.add(relative(DESKTOP_ROOT, archAbs).replaceAll('\\', '/'));
      }
    }
  }
  return [...paths].sort();
}

export function getRequiredArchPaths(): string[] {
  return [...new Set([...STATIC_ARCH_PATHS, ...discoverArchPathsUnderScanRoots()])].sort();
}

/** Core source files that must declare fractal [INPUT] headers. */
const CORE_IOP_PATHS = [
  'src-tauri/src/main.rs',
  'src-tauri/src/config.rs',
  'src-tauri/src/runtime/mod.rs',
  'src-tauri/src/runtime/python_backend.rs',
  'src-tauri/src/runtime/agent_runner.rs',
  'src-tauri/src/agent_runner_rpc/mod.rs',
  'src-tauri/src/runtime/appshot/mod.rs',
  'src-tauri/src/runtime/inline_input.rs',
  'src-tauri/src/runtime/watchdog.rs',
  'src-tauri/src/sessions/mod.rs',
  'src-tauri/src/app/mod.rs',
  'src-tauri/src/app/lifecycle.rs',
  'src-tauri/src/app/tray.rs',
  'src-tauri/src/runtime/nextjs_frontend.rs',
  'src-tauri/src/cli_agent_types.rs',
  'src-tauri/src/utils/updater_safety.rs',
  'src-tauri/src/commands/mod.rs',
  'src-tauri/src/commands/agent/mod.rs',
  'src-tauri/src/permissions/mod.rs',
  'src-tauri/src/utils/mod.rs',
  'src-tauri/src/agent_runner_rpc/types.rs',
  'src-tauri/src/agent_runner_rpc/transport.rs',
  'scripts/check-fractal-docs.ts',
] as const;

/**
 * Core security and command-registration files that must be tracked by git.
 * Prevents shipping partial IPC hardening when key files are left as `??`.
 */
const STATIC_CORE_TRACKED_PATHS = [
  'src-tauri/build.rs',
  'src-tauri/command_registry_macro.in',
  'src-tauri/src/main.rs',
  'src-tauri/src/app/mod.rs',
  'src-tauri/src/commands/config.rs',
  'src-tauri/src/commands/recovery.rs',
  'src-tauri/src/ipc_security.rs',
] as const;

export function discoverAutogeneratedPermissionPaths(): string[] {
  if (!existsSync(AUTOGENERATED_PERMISSIONS_DIR)) {
    return [];
  }
  return readdirSync(AUTOGENERATED_PERMISSIONS_DIR)
    .filter((name) => name.endsWith('.toml'))
    .sort()
    .map((name) => `src-tauri/permissions/autogenerated/${name}`);
}

export function discoverRegistryCommandNames(): string[] {
  if (!existsSync(COMMAND_REGISTRY_PATH)) {
    return [];
  }
  const seen = new Set<string>();
  const source = readFileSync(COMMAND_REGISTRY_PATH, 'utf8');
  const matcher = /\(\s*"([^"]+)"\s*,/g;
  let match: RegExpExecArray | null;
  while ((match = matcher.exec(source)) !== null) {
    seen.add(match[1]);
  }
  return [...seen].sort();
}

export function getRequiredTrackedPaths(): string[] {
  return [...STATIC_CORE_TRACKED_PATHS, ...discoverAutogeneratedPermissionPaths()];
}

const LINE_BUDGET_BASELINE_PATH = join(import.meta.dir, 'ci', 'rust_line_budget_baseline.txt');
const FRACTAL_DOCS_BASELINE_PATH = join(import.meta.dir, 'ci', 'fractal_docs_baseline.txt');

function loadBaseline(path: string): Set<string> {
  if (!existsSync(path)) {
    return new Set();
  }
  const entries = new Set<string>();
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const stripped = line.trim();
    if (!stripped || stripped.startsWith('#')) {
      continue;
    }
    entries.add(stripped);
  }
  return entries;
}

function isPrunedDir(dirName: string, relParts: string[]): boolean {
  if (PRUNE_DIR_NAMES.has(dirName)) {
    return true;
  }
  return relParts.some((part) => PRUNE_DIR_NAMES.has(part));
}

function hasSourceFile(dir: string): boolean {
  for (const entry of readdirSync(dir)) {
    const abs = join(dir, entry);
    if (!statSync(abs).isFile()) {
      continue;
    }
    const dot = entry.lastIndexOf('.');
    if (dot < 0) {
      continue;
    }
    const ext = entry.slice(dot);
    if (!SOURCE_EXTENSIONS.has(ext)) {
      continue;
    }
    if (entry.includes('.test.') || entry.includes('.spec.')) {
      continue;
    }
    return true;
  }
  return false;
}

function collectDirsUnder(absRoot: string): string[] {
  const dirs: string[] = [absRoot];

  function walk(absDir: string): void {
    for (const entry of readdirSync(absDir)) {
      const abs = join(absDir, entry);
      if (!statSync(abs).isDirectory()) {
        continue;
      }
      const relParts = relative(DESKTOP_ROOT, abs).replaceAll('\\', '/').split('/');
      if (isPrunedDir(entry, relParts)) {
        continue;
      }
      dirs.push(abs);
      walk(abs);
    }
  }

  walk(absRoot);
  return dirs;
}

export function collectRecursiveArchGaps(baseline: Set<string> = loadFractalDocsBaseline()): string[] {
  const gaps: string[] = [];

  for (const relRoot of RECURSIVE_SCAN_ROOTS) {
    const absRoot = join(DESKTOP_ROOT, relRoot);
    if (!existsSync(absRoot)) {
      continue;
    }
    for (const absDir of collectDirsUnder(absRoot)) {
      if (!hasSourceFile(absDir)) {
        continue;
      }
      const rel = relative(DESKTOP_ROOT, absDir).replaceAll('\\', '/');
      if (existsSync(join(absDir, '_ARCH.md'))) {
        continue;
      }
      if (baseline.has(rel)) {
        continue;
      }
      gaps.push(rel);
    }
  }

  return gaps.sort();
}

export function loadFractalDocsBaseline(): Set<string> {
  return loadBaseline(FRACTAL_DOCS_BASELINE_PATH);
}

function collectRustSourceFiles(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const abs = join(dir, entry);
    const st = statSync(abs);
    if (st.isDirectory()) {
      if (isPrunedDir(entry, relative(DESKTOP_ROOT, abs).replaceAll('\\', '/').split('/'))) {
        continue;
      }
      collectRustSourceFiles(abs, acc);
    } else if (entry.endsWith('.rs')) {
      acc.push(abs);
    }
  }
  return acc;
}

function countLines(absPath: string): number {
  return readFileSync(absPath, 'utf8').split('\n').length;
}

function readDocHead(relPath: string, scanLines = HEADER_SCAN_LINES): string {
  const abs = join(DESKTOP_ROOT, relPath);
  return readFileSync(abs, 'utf8')
    .split('\n')
    .slice(0, scanLines)
    .join('\n');
}

function hasInputHeader(relPath: string): boolean {
  return readDocHead(relPath).includes(INPUT_MARKER);
}

function hasPosHeader(relPath: string): boolean {
  return readDocHead(relPath).includes(POS_MARKER);
}

function isGitTracked(relPath: string): boolean {
  const result = spawnSync('git', ['ls-files', '--error-unmatch', '--', relPath], {
    cwd: DESKTOP_ROOT,
    stdio: 'ignore',
  });
  return result.status === 0;
}

export function collectFractalDocViolations(): string[] {
  const errors: string[] = [];
  const autogeneratedPermissions = discoverAutogeneratedPermissionPaths();
  const registryCommands = discoverRegistryCommandNames();

  for (const rel of getRequiredArchPaths()) {
    const abs = join(DESKTOP_ROOT, rel);
    if (!existsSync(abs)) {
      errors.push(`missing required doc: ${rel}`);
      continue;
    }
    if (!hasPosHeader(rel)) {
      errors.push(`missing ${POS_MARKER} in first ${HEADER_SCAN_LINES} lines: ${rel}`);
    }
  }

  for (const rel of collectRecursiveArchGaps()) {
    errors.push(`recursive scan: directory with source missing _ARCH.md: ${rel}`);
  }

  for (const rel of CORE_IOP_PATHS) {
    const abs = join(DESKTOP_ROOT, rel);
    if (!existsSync(abs)) {
      errors.push(`missing core file for IOP check: ${rel}`);
      continue;
    }
    if (!hasInputHeader(rel)) {
      errors.push(`missing ${INPUT_MARKER} in first ${HEADER_SCAN_LINES} lines: ${rel}`);
    }
  }

  if (autogeneratedPermissions.length === 0) {
    errors.push('missing autogenerated permission ACL files: src-tauri/permissions/autogenerated/*.toml');
  }
  if (registryCommands.length === 0) {
    errors.push('missing command registry entries: src-tauri/command_registry_macro.in');
  }

  const permissionSet = new Set(autogeneratedPermissions.map((path) => path.split('/').at(-1) ?? ''));
  for (const command of registryCommands) {
    const expected = `${command}.toml`;
    if (!permissionSet.has(expected)) {
      errors.push(
        `missing autogenerated permission ACL for command "${command}": src-tauri/permissions/autogenerated/${expected}`,
      );
    }
  }
  const registrySet = new Set(registryCommands);
  for (const rel of autogeneratedPermissions) {
    const fileName = rel.split('/').at(-1);
    if (!fileName || !fileName.endsWith('.toml')) {
      continue;
    }
    const commandName = fileName.slice(0, -'.toml'.length);
    if (!registrySet.has(commandName)) {
      errors.push(
        `stale autogenerated permission ACL without command registration: src-tauri/permissions/autogenerated/${fileName}`,
      );
    }
  }

  for (const rel of getRequiredTrackedPaths()) {
    const abs = join(DESKTOP_ROOT, rel);
    if (!existsSync(abs)) {
      errors.push(`missing core tracked file: ${rel}`);
      continue;
    }
    if (!isGitTracked(rel)) {
      errors.push(`core tracked file is not committed/tracked by git: ${rel}`);
    }
  }

  const lineBudgetBaseline = loadBaseline(LINE_BUDGET_BASELINE_PATH);
  const rustFiles = collectRustSourceFiles(RUST_SRC_ROOT);
  for (const abs of rustFiles) {
    const rel = relative(DESKTOP_ROOT, abs).replaceAll('\\', '/');
    const lines = countLines(abs);
    if (lines > MAX_LINES && !lineBudgetBaseline.has(rel)) {
      errors.push(`line budget exceeded (${lines} > ${MAX_LINES}): ${rel}`);
    }
  }

  return errors;
}

export function assertFractalDocsCompliant(): void {
  const errors = collectFractalDocViolations();
  if (errors.length > 0) {
    throw new Error(`Fractal documentation gate failed:\n${errors.join('\n')}`);
  }
}

export function writeFractalDocsBaseline(): number {
  const gaps = collectRecursiveArchGaps(new Set());
  mkdirSync(join(import.meta.dir, 'ci'), { recursive: true });
  const body = [
    '# Desktop-relative directories grandfathered without _ARCH.md (one per line)',
    '# Regenerate gaps: bun run scripts/check-fractal-docs.ts --write-baseline',
    ...gaps,
    '',
  ].join('\n');
  writeFileSync(FRACTAL_DOCS_BASELINE_PATH, body, 'utf8');
  return gaps.length;
}

if (import.meta.main) {
  if (process.argv.includes('--write-baseline')) {
    const count = writeFractalDocsBaseline();
    console.log(`Wrote ${count} entries to ${relative(DESKTOP_ROOT, FRACTAL_DOCS_BASELINE_PATH)}`);
    process.exit(0);
  }

  const errors = collectFractalDocViolations();
  if (errors.length > 0) {
    console.error('Fractal documentation gate failed:\n' + errors.join('\n'));
    process.exit(1);
  }
  const requiredArch = getRequiredArchPaths();
  const requiredTracked = getRequiredTrackedPaths();
  console.log(
    `Fractal docs OK (${requiredArch.length} required arch, ${RECURSIVE_SCAN_ROOTS.length} recursive roots, ${CORE_IOP_PATHS.length} IOP files, ${requiredTracked.length} tracked core files, line budget ${MAX_LINES})`,
  );
}
