# [INPUT]: None
# [OUTPUT]: AdoptionChoice, AdoptionReceipt, AgentExecutionOutput, AgentRoleTarget, CrossExamArbitrationReport, CrossExamConsensus, CrossExamDivergence, IntentCategory, IntentRoutingDecision
# [POS]: agent/sub_agents/cross_examination/cross_exam_types.py

"""Domain contracts and models for omni-agent unified dispatch and split cross-examination suite.

[INPUT]
- None (Self-contained domain models).

[OUTPUT]
- AgentRoleTarget: Standard specialized agent archetypes (Coding, Research, Security, Local, Architect).
- IntentCategory: High-level classification of user requests.
- IntentRoutingDecision: Routing decision with confidence, candidate agents, and cross-exam suggestion.
- AgentExecutionOutput: Output payload of a single candidate agent.
- CrossExamConsensus: Common ground facts and shared recommendations across agents.
- CrossExamDivergence: Specific points of disagreement, positions, and severity.
- CrossExamArbitrationReport: Full cross-examination analysis with synthesis.
- AdoptionChoice: User choice on which verdict to adopt.
- AdoptionReceipt: Formatted adoption receipt ready for workspace context injection.

[POS]
Domain contract layer for Item 314 OmniAgentUnifiedDispatcherAndSplitCrossExaminationSuite.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Mapping, Sequence


class AgentRoleTarget(str, Enum):
    """Specialized agent roles available in the omni-agent ecosystem."""

    CODING_SPECIALIST = "coding_specialist"       # Deep implementation, refactoring, unit tests
    DEEP_RESEARCH = "deep_research"               # Broad survey, multi-source literature, citation
    SECURITY_CRITIC = "security_critic"           # Threat modeling, blast radius, destructive guard
    LOCAL_FAST = "local_fast"                     # Sub-100ms lightweight assistant, daily commands
    ARCHITECT_PLANNER = "architect_planner"       # High-level architecture, trade-off analysis


class IntentCategory(str, Enum):
    """Broad classification of query intent."""

    DEVELOPMENT_ENGINEERING = "development_engineering"
    RESEARCH_SURVEY = "research_survey"
    SECURITY_HIGH_RISK = "security_high_risk"
    ARCHITECTURAL_DECISION = "architectural_decision"
    GENERAL_QUICK_COMMAND = "general_quick_command"


class AdoptionChoice(str, Enum):
    """Adoption resolution mode."""

    LEAD_AGENT = "lead_agent"
    SPECIFIC_AGENT = "specific_agent"
    SYNTHESIZED_CONSENSUS = "synthesized_consensus"


@dataclass(frozen=True)
class IntentRoutingDecision:
    """Intelligent intent routing result from the unified single-entry dispatcher."""

    primary_agent: AgentRoleTarget
    confidence: float
    category: IntentCategory
    suggested_cross_exam_agents: Sequence[AgentRoleTarget]
    is_cross_exam_candidate: bool
    reasoning: str


@dataclass(frozen=True)
class AgentExecutionOutput:
    """Output generated by a single participant agent during cross-examination."""

    agent_role: AgentRoleTarget
    display_name: str
    content: str
    latency_ms: float
    key_claims: Sequence[str] = field(default_factory=tuple)


@dataclass(frozen=True)
class CrossExamConsensus:
    """Inter-agent agreements and common ground facts."""

    common_ground_facts: Sequence[str]
    shared_recommendations: Sequence[str]
    agreement_score: float  # 0.0 (total conflict) to 1.0 (unanimous agreement)


@dataclass(frozen=True)
class CrossExamDivergence:
    """A specific contested dimension or contradiction across agents."""

    topic: str
    agent_positions: Mapping[AgentRoleTarget, str]
    severity: str           # "low", "medium", "critical"
    risk_level: str         # "info", "warning", "high_risk"


@dataclass(frozen=True)
class CrossExamArbitrationReport:
    """Consolidated cross-examination dashboard data."""

    query: str
    agent_outputs: Sequence[AgentExecutionOutput]
    consensus: CrossExamConsensus
    divergences: Sequence[CrossExamDivergence]
    synthesized_recommendation: str
    recommended_lead_agent: AgentRoleTarget


@dataclass(frozen=True)
class AdoptionReceipt:
    """Structured receipt representing the final adopted decision."""

    choice: AdoptionChoice
    adopted_agent: AgentRoleTarget | None
    adopted_summary: str
    context_injection_block: str
