"""[POS]: src/myrm_agent_harness/toolkits/memory/four_tier_fts/models.py
[INPUT]: Memory scope enums, items, search parameters, and compaction reports.
[OUTPUT]: Immutable models for 4-tier persistent memory, SQLite FTS5 search hits, and dream compaction reports.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum


class MemoryScope(StrEnum):
    """Four-tier decoupled persistence scopes per MiMo architecture."""

    GLOBAL = "global"  # Cross-project universal user preferences and profiles
    PROJECT = "project"  # Codebase/repository specific conventions and architecture rules
    SESSION = "session"  # Checkpoints and state snapshots for crash recovery
    PROGRESS = "progress"  # Dynamic goal progress and todos resisting context compaction


@dataclass
class FourTierMemoryItem:
    """Individual memory item belonging to one of the 4 persistent tiers."""

    item_id: str
    scope: MemoryScope
    title: str
    content: str
    project_hash: str = "default"
    session_id: str = ""
    tags: list[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))


@dataclass(frozen=True)
class FtsSearchResult:
    """Ranked hit returned from SQLite FTS5 full-text search query."""

    item_id: str
    scope: MemoryScope
    project_hash: str
    title: str
    content: str
    snippet: str
    bm25_rank: float
    updated_at: datetime


@dataclass(frozen=True)
class DreamCompactionReport:
    """Audit report generated by a /dream maintenance and compaction cycle."""

    dream_id: str
    scanned_items_count: int
    merged_items_count: int
    pruned_items_count: int
    retained_items_count: int
    duration_ms: float
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
