"""Data models for Bitable / Spreadsheet Sidebar Interactive CoPilot.

Defines table schema, fields, cell mutations, and batch wrangling intents.

[INPUT]
- pydantic::BaseModel, Field
- typing::Any, Dict, List, Optional, Literal

[OUTPUT]
- TableFieldSchema, TableRowData, TableContextPayload, CellMutation, BatchWranglingResult

[POS]
Core models for Bitable Sidebar CoPilot domain.
"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field


class TableFieldSchema(BaseModel):
    """Schema definition for a single table column/field."""

    field_id: str = Field(..., description="Unique identifier of the field")
    name: str = Field(..., description="Display name of the field")
    field_type: Literal[
        "text", "number", "single_select", "multi_select", "date", "checkbox", "url", "formula"
    ] = Field(default="text", description="Field data type")
    description: Optional[str] = Field(default=None, description="Optional field description")
    options: List[str] = Field(default_factory=list, description="Available options for select fields")


class TableRowData(BaseModel):
    """Data content of a single row in the table."""

    row_id: str = Field(..., description="Unique row identifier")
    cells: Dict[str, Any] = Field(default_factory=dict, description="Map of field_id to cell value")
    is_selected: bool = Field(default=False, description="Whether this row is currently selected in UI")


class TableContextPayload(BaseModel):
    """Full context captured from active Bitable / spreadsheet view."""

    table_id: str = Field(..., description="Identifier of the active table")
    table_name: str = Field(..., description="Display name of the table")
    fields: List[TableFieldSchema] = Field(default_factory=list, description="All visible fields")
    rows: List[TableRowData] = Field(default_factory=list, description="Active or filtered rows")
    active_field_id: Optional[str] = Field(default=None, description="Currently focused column")
    selected_row_ids: List[str] = Field(default_factory=list, description="Explicitly selected row IDs")


class CellMutation(BaseModel):
    """A single cell update proposal generated by the CoPilot."""

    row_id: str = Field(..., description="Target row ID")
    field_id: str = Field(..., description="Target field ID")
    old_value: Optional[Any] = Field(default=None, description="Original value before change")
    new_value: Any = Field(..., description="Suggested new value")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Model confidence score")
    reasoning: Optional[str] = Field(default=None, description="Short explanation for this change")


class BatchWranglingResult(BaseModel):
    """Aggregated result of AI data processing across rows."""

    task_id: str = Field(..., description="Unique wrangling task execution ID")
    table_id: str = Field(..., description="Target table ID")
    target_field_id: str = Field(..., description="Field receiving the mutated data")
    mutations: List[CellMutation] = Field(default_factory=list, description="List of proposed cell edits")
    summary: str = Field(..., description="Human readable summary of changes performed")
    total_processed: int = Field(default=0, description="Count of rows evaluated")
    total_mutated: int = Field(default=0, description="Count of rows with actual proposed changes")
