"""[POS]: app/schemas/disk_reconciliation.py
[INPUT]: Pydantic BaseModel, Field, datetime, and typing primitives.
[OUTPUT]: Request and response DTO schemas for disk memory reconciliation loops, write-gate policies, and FTS search.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, Field


class WriteGatePolicyEnum(StrEnum):
    """Explicit typed gate policies governing whether new persistent memory writes are permitted."""

    ENABLED = "enabled"
    READ_ONLY_SESSION = "read_only_session"
    DISABLED_TEMPORARY = "disabled_temporary"
    DISABLED_CONFIG_FAULT = "disabled_config_fault"


class WriteGateCheckResultDTO(BaseModel):
    """Outcome report evaluating whether a memory write is authorized."""

    is_allowed: bool = Field(description="True if memory writes are permitted under active policy")
    policy: str = Field(description="Active policy enum string")
    reason: str = Field(description="Human-readable rationale for the gate decision")


class SetWriteGatePolicyRequestDTO(BaseModel):
    """Request payload to update write gate policy globally or for a specific session."""

    policy: str = Field(description="Target policy: enabled, read_only_session, disabled_temporary, disabled_config_fault")
    session_id: str | None = Field(default=None, description="Optional target session ID for session-scoped override")


class ReconciliationReportDTO(BaseModel):
    """Audit report generated by a bi-directional disk-memory FTS reconciliation loop."""

    reconcile_id: str = Field(description="Unique reconciliation pass identifier")
    scanned_disk_files_count: int = Field(ge=0, description="Total physical markdown files discovered on disk")
    indexed_or_updated_count: int = Field(ge=0, description="Files newly indexed or updated due to fingerprint changes (Direction A)")
    pruned_dead_rows_count: int = Field(ge=0, description="Dead FTS rows physically purged for removed files (Direction B)")
    duration_ms: float = Field(ge=0.0, description="Reconciliation loop execution duration in milliseconds")
    status: str = Field(description="Execution status: completed or blocked_by_write_gate")
    created_at: datetime = Field(description="Pass execution timestamp")


class TriggerReconciliationRequestDTO(BaseModel):
    """Payload to trigger a bi-directional reconciliation pass over disk directories."""

    roots: list[str] = Field(default_factory=list, description="List of directory paths to scan on disk")
    session_id: str | None = Field(default=None, description="Optional session context to verify write permissions")


class FtsReconciledHitDTO(BaseModel):
    """Ranked search hit from reconciled FTS full-text virtual table."""

    file_path: str = Field(description="Physical file path of matched markdown note")
    title: str = Field(description="Title extracted from document header or frontmatter")
    snippet: str = Field(description="Highlighted snippet of matched content")
    rank_score: float = Field(description="Relevance ranking score")


class ReconciliationStatsDTO(BaseModel):
    """Summary metrics of the disk reconciliation index."""

    total_indexed_files: int = Field(ge=0, description="Total currently indexed active markdown notes")
    global_write_policy: str = Field(description="Current global write gate policy")
