"""Pydantic schemas for External Plugin Guardrail Auditing and Migration Doctor.

[INPUT]
- None (Self-contained schema representations for plugin guardrail requests and responses)

[OUTPUT]
- PluginManifestModel, PluginAuditRequest, PluginAuditReportResponse, MigrationDiagnoseRequest, MigrationDoctorReportResponse, MigrationExecuteRequest, MigrationExecuteResponse

[POS]
- app.schemas.plugin_guardrail
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class PluginManifestModel(BaseModel):
    """Manifest specification of an external plugin."""

    plugin_id: str = Field(..., description="Unique plugin identifier")
    name: str = Field(..., description="Plugin display name")
    version: str = Field(..., description="Plugin semantic release version")
    author: str = Field(..., description="Plugin author or maintainer")
    entrypoint: str = Field(..., description="Main Python execution file, e.g. main.py")
    declared_scopes: list[str] = Field(
        default_factory=list,
        description="Declared capability scopes (e.g. NETWORK_EGRESS, FILESYSTEM_READ)",
    )
    allowed_egress_hosts: list[str] = Field(
        default_factory=list,
        description="Whitelisted outbound destination domains",
    )
    required_env_keys: list[str] = Field(
        default_factory=list,
        description="Required environment variable identifiers",
    )


class PluginAuditRequest(BaseModel):
    """Request payload to perform static security auditing on plugin code."""

    manifest: PluginManifestModel = Field(..., description="Plugin manifest declaration")
    code_files: dict[str, str] = Field(
        ...,
        description="Mapping from relative file path to file content string",
    )


class AuditFindingModel(BaseModel):
    """Detail of a single security finding or rule violation."""

    severity: str = Field(..., description="Severity level: INFO, WARNING, or CRITICAL")
    rule_id: str = Field(..., description="Rule identifier (e.g. SEC-001)")
    description: str = Field(..., description="Rule violation description")
    file_path: str | None = Field(default=None, description="Source file path")
    line_number: int | None = Field(default=None, description="Line number if located")


class PluginAuditReportResponse(BaseModel):
    """Outcome of static code analysis and assigned safety rating."""

    plugin_id: str = Field(..., description="Target plugin identifier")
    safety_rating: str = Field(..., description="Assigned safety rating: A_EXCELLENT, B_GOOD, C_ELEVATED_RISK, F_UNTRUSTED")
    is_install_allowed: bool = Field(..., description="Whether the plugin meets safety admission gate")
    findings: list[AuditFindingModel] = Field(
        default_factory=list,
        description="List of detected vulnerabilities and AST findings",
    )
    scanned_files_count: int = Field(..., description="Number of audited code files")
    audit_timestamp: float = Field(..., description="UNIX timestamp of audit")


class MigrationDiagnoseRequest(BaseModel):
    """Payload to diagnose legacy plugin state and memory compatibility."""

    plugin_id: str = Field(..., description="Target plugin identifier")
    legacy_config: dict[str, str] = Field(
        default_factory=dict,
        description="Legacy unmigrated plugin configuration dictionary",
    )
    legacy_env: dict[str, str] = Field(
        default_factory=dict,
        description="Legacy unmigrated environment variables",
    )
    memory_records_count: int = Field(
        default=0,
        description="Count of active user memory vectors associated with this plugin",
    )


class MigrationDiagnosticItemModel(BaseModel):
    """Status assessment of an individual state component."""

    target: str = Field(..., description="Component evaluated (plugin_config, env_vars, memory_vector_store)")
    status: str = Field(..., description="HEALTHY, COMPATIBLE_NEEDS_UPGRADE, or CORRUPTED")
    details: str = Field(..., description="Observation details")
    remediation_available: bool = Field(..., description="Whether automated repair is supported")


class MigrationDoctorReportResponse(BaseModel):
    """Diagnostic outcome generated by the Migration Doctor."""

    plugin_id: str = Field(..., description="Target plugin identifier")
    is_migration_ready: bool = Field(..., description="Whether system can smoothly execute zero-loss migration")
    diagnostics: list[MigrationDiagnosticItemModel] = Field(
        default_factory=list,
        description="Component-level health diagnostics",
    )
    auto_remediated_count: int = Field(..., description="Number of items needing automated remediation")
    notes: list[str] = Field(
        default_factory=list,
        description="Doctor summary notes and instructions",
    )


class MigrationExecuteRequest(BaseModel):
    """Payload to execute automated zero-loss migration adaptation."""

    plugin_id: str = Field(..., description="Target plugin identifier")
    legacy_config: dict[str, str] = Field(default_factory=dict, description="Legacy configuration dictionary")
    legacy_env: dict[str, str] = Field(default_factory=dict, description="Legacy environment variables")


class MigrationExecuteResponse(BaseModel):
    """Result of zero-loss migration execution."""

    plugin_id: str = Field(..., description="Target plugin identifier")
    modernized_config: dict[str, str] = Field(..., description="Migrated clean configuration dictionary")
    modernized_env: dict[str, str] = Field(..., description="Migrated namespaced environment variables")
    migration_logs: list[str] = Field(default_factory=list, description="Step-by-step migration audit logs")
