"""Type definitions for Autonomous Bot Asset Security Boundary and Wallet Credential Air-Gap Guard.

[INPUT]
- None.

[OUTPUT]
- FinancialActionType, WalletKeyType, SpendingCeilingPolicy
- FinancialTransactionIntent, TransactionEvaluationResult, FinancialConfirmationCard
- FinancialActionBoundaryError, DailySpendCeilingExceededError, AirGappedCredentialViolationError

[POS]
- Harness core security module inspired by Hermes/Telegram crypto bot risk management.
- Strictly separates agent analysis from transaction signing, prohibits private keys in prompt context,
  and enforces daily spending circuit breakers with interactive two-person confirmation cards.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import StrEnum


class FinancialActionType(StrEnum):
    """Categorization of financial/asset actions."""

    TRANSFER = "transfer"
    TRADE = "trade"
    SWAP = "swap"
    APPROVE_ALLOWANCE = "approve_allowance"
    BUY = "buy"
    WITHDRAW = "withdraw"


class WalletKeyType(StrEnum):
    """Classification of wallet keys in relation to agent execution scope."""

    READ_ONLY_WATCHER = "read_only_watcher"  # Safe: balance & transaction monitoring only
    HOT_SIGNER = "hot_signer"  # Dangerous: auto-signing capability for micro-transactions
    AIR_GAPPED_VAULT = "air_gapped_vault"  # Highest security: physical multi-sig / cold storage


@dataclass(frozen=True, slots=True)
class SpendingCeilingPolicy:
    """Hard parameters controlling autonomous micro-transactions and circuit breakers."""

    daily_ceiling_usd: float = 50.0
    single_transaction_ceiling_usd: float = 5.0
    require_two_person_confirmation_above_usd: float = 5.0
    allowed_asset_symbols: frozenset[str] = frozenset({
        "USDC",
        "USDT",
        "ETH",
        "SOL",
        "BTC",
        "USD",
        "CNY",
    })


@dataclass(frozen=True, slots=True)
class FinancialTransactionIntent:
    """Structured proposal generated by an agent seeking to execute a financial movement."""

    intent_id: str
    task_id: str
    action_type: FinancialActionType
    asset_symbol: str
    amount: float
    estimated_usd_value: float
    recipient_address: str
    justification: str
    created_at: float = field(default_factory=time.time)


@dataclass(frozen=True, slots=True)
class FinancialConfirmationCard:
    """Human-in-the-loop multi-factor confirmation card pushed to IM channels."""

    card_id: str
    intent: FinancialTransactionIntent
    status: str  # pending, approved, rejected, expired
    created_at: float = field(default_factory=time.time)
    expires_at: float = field(default_factory=lambda: time.time() + 300.0)


@dataclass(frozen=True, slots=True)
class TransactionEvaluationResult:
    """Evaluation verdict detailing whether an asset movement is allowed, blocked, or requires sign-off."""

    intent_id: str
    permitted_autonomous_execution: bool
    requires_human_confirmation: bool
    circuit_breaker_triggered: bool
    current_daily_spend_usd: float
    remaining_daily_limit_usd: float
    reason: str
    confirmation_card_id: str | None = None


class FinancialActionBoundaryError(Exception):
    """Base exception for asset boundary violations."""


class AirGappedCredentialViolationError(FinancialActionBoundaryError):
    """Raised when an agent attempts to load, read, or pass private keys or mnemonic seeds."""


class DailySpendCeilingExceededError(FinancialActionBoundaryError):
    """Raised when an operation would exceed daily spending ceiling limits."""
