import platform
import shutil
import subprocess
from pathlib import Path


def print_header(text: str) -> None:
    """打印标题"""
    print(f"\n{'=' * 60}")
    print(f"  {text}")
    print(f"{'=' * 60}\n")


def print_step(step: int, text: str) -> None:
    """打印步骤"""
    print(f"\n[{step}] {text}")
    print("-" * 40)


def print_success(text: str) -> None:
    """打印成功信息"""
    print(f"✅ {text}")


def print_warning(text: str) -> None:
    """打印警告信息"""
    print(f"⚠️  {text}")


def print_error(text: str) -> None:
    """打印错误信息"""
    print(f"❌ {text}")


def print_info(text: str) -> None:
    """打印信息"""
    print(f"ℹ️  {text}")


def run_command(cmd: list[str], check: bool = True, capture: bool = False) -> subprocess.CompletedProcess[str]:
    """运行命令"""
    try:
        result = subprocess.run(
            cmd,
            check=check,
            capture_output=capture,
            text=True,
        )
        return result
    except subprocess.CalledProcessError as e:
        if capture:
            print_error(f"Command failed: {' '.join(cmd)}")
            if e.stdout:
                print(f"stdout: {e.stdout}")
            if e.stderr:
                print(f"stderr: {e.stderr}")
        raise


def command_exists(cmd: str) -> bool:
    """检查命令是否存在"""
    return shutil.which(cmd) is not None


def merge_env_files(base_files: list[Path], output_file: Path) -> None:
    """合并多个环境变量文件

    后面的文件会覆盖前面的配置
    支持带引号的值和空值

    Args:
        base_files: 按优先级排序的环境变量文件列表（后面覆盖前面）
        output_file: 输出文件路径
    """
    merged: dict[str, str] = {}

    for env_file in base_files:
        if not env_file.exists():
            print_info(f"跳过不存在的文件: {env_file.name}")
            continue

        print_info(f"加载配置: {env_file.name}")

        with open(env_file, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()

                # 跳过注释和空行
                if not line or line.startswith("#"):
                    continue

                # 解析 KEY=VALUE
                if "=" in line:
                    key, _, value = line.partition("=")
                    key = key.strip()
                    value = value.strip()

                    # 处理引号包裹的值
                    if value.startswith('"') and value.endswith('"'):
                        value = value[1:-1]
                    elif value.startswith("'") and value.endswith("'"):
                        value = value[1:-1]

                    # 跳过模板占位符
                    if value.startswith("your-") or value.startswith("YOUR_"):
                        continue

                    # 空值也保留（可能是有意禁用某功能）
                    merged[key] = value

    # 写入输出文件
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("# =============================================================================\n")
        f.write("# Auto-generated by deploy.py - DO NOT EDIT DIRECTLY\n")
        f.write("# =============================================================================\n")
        f.write(f"# Merged from: {', '.join(p.name for p in base_files if p.exists())}\n")
        f.write("# To modify, edit the source files and re-run deploy.py\n")
        f.write("# =============================================================================\n\n")

        for key, value in sorted(merged.items()):
            # 如果值包含特殊字符，用引号包裹
            if " " in value or '"' in value or "'" in value:
                f.write(f'{key}="{value}"\n')
            else:
                f.write(f"{key}={value}\n")

    print_success(f"已生成 {output_file.name} (合并了 {len(merged)} 个配置项)")


def get_os_type() -> str:
    """获取操作系统类型"""
    system = platform.system().lower()
    if system == "darwin":
        return "macos"
    elif system == "linux":
        return "linux"
    elif system == "windows":
        return "windows"
    else:
        return "unknown"
