"""Transpiler detecting conflicts and consolidating multi-ecosystem rule files into AGENTS.md."""

from __future__ import annotations

import hashlib
import re
from typing import Dict, List, Set, Tuple

from .cross_ecosystem_types import (
    DiscoveredEcosystemFile,
    EcosystemConflictItem,
    RuleSectionCategory,
)


class CrossEcosystemTranspiler:
    """Detects semantic rule conflicts and transpiles foreign rules into standardized AGENTS.md."""

    def detect_conflicts(
        self,
        files: List[DiscoveredEcosystemFile],
    ) -> List[EcosystemConflictItem]:
        """Detect conflicting package managers, test runners, or restrictions across files."""
        conflicts: List[EcosystemConflictItem] = []
        if len(files) < 2:
            return conflicts

        # Extract build & test command keywords
        commands_by_file: Dict[str, Set[str]] = {}
        for f in files:
            build_text = f.parsed_sections.get(RuleSectionCategory.BUILD_AND_TEST, f.content)
            found_cmds = set()
            for pkg in ["pnpm", "yarn", "npm", "bun", "poetry", "uv", "pip", "cargo", "mvn", "gradle"]:
                if re.search(rf"\b{pkg}\b", build_text.lower()):
                    found_cmds.add(pkg)
            if found_cmds:
                commands_by_file[f.file_path] = found_cmds

        # Compare pairs
        file_paths = list(commands_by_file.keys())
        for i in range(len(file_paths)):
            for j in range(i + 1, len(file_paths)):
                fa, fb = file_paths[i], file_paths[j]
                diff_a = commands_by_file[fa] - commands_by_file[fb]
                diff_b = commands_by_file[fb] - commands_by_file[fa]
                if diff_a and diff_b:
                    conflicts.append(
                        EcosystemConflictItem(
                            category=RuleSectionCategory.BUILD_AND_TEST,
                            file_a=fa,
                            file_b=fb,
                            conflict_description=(
                                f"Conflicting package managers/tools detected: {sorted(diff_a)} vs {sorted(diff_b)}"
                            ),
                            suggested_resolution="Consolidate to a single package manager across the repository.",
                        )
                    )

        return conflicts

    def transpile_to_standard_agents_md(
        self,
        files: List[DiscoveredEcosystemFile],
    ) -> str:
        """Consolidate multiple rule files into a unified standard AGENTS.md format."""
        if not files:
            return "# AGENTS.md\n\nNo workspace rules defined."

        # Group sections
        categorized_blocks: Dict[RuleSectionCategory, List[Tuple[str, str]]] = {
            RuleSectionCategory.PROJECT_OVERVIEW: [],
            RuleSectionCategory.BUILD_AND_TEST: [],
            RuleSectionCategory.CODE_STYLE: [],
            RuleSectionCategory.RESTRICTIONS_GUARD: [],
            RuleSectionCategory.CUSTOM_DIRECTIVE: [],
        }

        for f in files:
            for cat, text in f.parsed_sections.items():
                if text.strip():
                    categorized_blocks[cat].append((f.file_path, text))

        doc_lines: List[str] = [
            "<!-- Standardized AGENTS.md Generated by Myrm Cross-Ecosystem Migration Engine -->",
            "# AGENTS.md\n",
        ]

        # 1. Project Overview
        if categorized_blocks[RuleSectionCategory.PROJECT_OVERVIEW]:
            doc_lines.append("## Project Overview\n")
            for src, block in categorized_blocks[RuleSectionCategory.PROJECT_OVERVIEW]:
                doc_lines.append(f"> Source: `{src}`\n{block}\n")

        # 2. Build & Test Commands
        if categorized_blocks[RuleSectionCategory.BUILD_AND_TEST]:
            doc_lines.append("## Build and Test Commands\n")
            for src, block in categorized_blocks[RuleSectionCategory.BUILD_AND_TEST]:
                doc_lines.append(f"<!-- Source: {src} -->\n{block}\n")

        # 3. Code Style & Engineering Standards
        if categorized_blocks[RuleSectionCategory.CODE_STYLE]:
            doc_lines.append("## Code Style & Engineering Standards\n")
            for src, block in categorized_blocks[RuleSectionCategory.CODE_STYLE]:
                doc_lines.append(f"<!-- Source: {src} -->\n{block}\n")

        # 4. Restrictions & Guardrails
        if categorized_blocks[RuleSectionCategory.RESTRICTIONS_GUARD]:
            doc_lines.append("## Security & Safety Guardrails\n")
            for src, block in categorized_blocks[RuleSectionCategory.RESTRICTIONS_GUARD]:
                doc_lines.append(f"<!-- Source: {src} -->\n{block}\n")

        # 5. Native & Custom Directives
        doc_lines.append("## Imported Ecosystem Sources\n")
        for f in files:
            doc_lines.append(f"### Ecosystem: `{f.ecosystem.value}` (`{f.file_path}`)\n")
            doc_lines.append("```markdown")
            doc_lines.append(f.content.strip())
            doc_lines.append("```\n")

        return "\n".join(doc_lines).strip()
