"""MCP server endpoint for external agent memory access.

[INPUT]
- myrm_agent_harness.toolkits.memory.mcp_server::MemoryMCPServer (POS: MCP adapter)
- app.services.connect::get_connect_service (POS: Token verification)
- app.core.memory.adapters.setup::create_memory_manager, resolve_memory_binding (POS: MemoryManager factory)

[OUTPUT]
- setup_mcp_endpoint: async init + mount on FastAPI app
- shutdown_mcp_endpoint: cancel session manager task group

[POS]
Exposes the memory system as a Streamable HTTP MCP endpoint that external
agents (Claude Code, Cursor, etc.) can connect to. Uses token-based
authentication via Bearer tokens generated by ConnectService.
The endpoint is mounted at /mcp on the FastAPI application during startup.

FastAPI's mount() does not propagate lifespan events to sub-apps, so we
manually start the MCP session manager's task group via a background task
and cancel it on shutdown.
"""

from __future__ import annotations

import asyncio
import logging
from typing import TYPE_CHECKING

from starlette.requests import Request
from starlette.responses import JSONResponse
from starlette.types import ASGIApp, Receive, Scope, Send

if TYPE_CHECKING:
    from fastapi import FastAPI

logger = logging.getLogger(__name__)

_session_manager_task: asyncio.Task[None] | None = None
_session_manager_ready = asyncio.Event()


class _MCPTokenAuthMiddleware:
    """ASGI middleware validating Bearer tokens for MCP requests."""

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        request = Request(scope)
        auth_header = request.headers.get("authorization", "")

        if not auth_header.startswith("Bearer "):
            response = JSONResponse(
                {"error": "Missing or invalid Authorization header"},
                status_code=401,
            )
            await response(scope, receive, send)
            return

        token = auth_header[7:]
        from app.services.connect import get_connect_service

        service = get_connect_service()
        profile_id = service.verify_token(token)
        if not profile_id:
            response = JSONResponse(
                {"error": "Invalid or revoked token"},
                status_code=403,
            )
            await response(scope, receive, send)
            return

        scope["state"] = scope.get("state", {})
        scope["state"]["mcp_profile_id"] = profile_id

        service.mark_ready(profile_id)

        await self.app(scope, receive, send)


async def setup_mcp_endpoint(app: FastAPI) -> None:
    """Create and mount the MCP memory endpoint at /mcp.

    Should be called during application startup (Phase 2 or later).
    Gracefully skips if memory system is not available.
    """
    global _session_manager_task

    try:
        from myrm_agent_harness.toolkits.memory.mcp_server import MemoryMCPServer

        from app.core.memory.adapters.setup import create_memory_manager, resolve_memory_binding
        from app.services.agent.platform_config import require_platform_embedding_config

        embedding_cfg = await require_platform_embedding_config()

        binding = resolve_memory_binding(
            namespaces=None,
            agent_id=None,
            channel_id=None,
            conversation_id=None,
            task_id=None,
        )
        memory_manager = await create_memory_manager(
            binding,
            embedding_cfg,
            approval_required=False,
        )

        mcp_server = MemoryMCPServer(memory_manager)
        mcp_asgi_app = mcp_server.get_streamable_http_app()

        # FastAPI mount() does not propagate lifespan to sub-apps, so the
        # Starlette sub-app's lifespan (which calls session_manager.run())
        # never fires. We start the session manager manually via a background
        # task that keeps the anyio TaskGroup alive for the server lifetime.
        sm = mcp_server.mcp.session_manager
        if sm is not None:

            async def _run_session_manager() -> None:
                async with sm.run():
                    _session_manager_ready.set()
                    # Block until cancelled on shutdown
                    await asyncio.Event().wait()

            _session_manager_task = asyncio.create_task(_run_session_manager())
            await asyncio.wait_for(_session_manager_ready.wait(), timeout=5.0)

        authed_app = _MCPTokenAuthMiddleware(mcp_asgi_app)
        app.mount("/mcp", authed_app)
        logger.info("MCP memory endpoint mounted at /mcp")

    except Exception as e:
        logger.warning("MCP endpoint not mounted (memory system unavailable): %s", e)


async def shutdown_mcp_endpoint() -> None:
    """Cancel the MCP session manager background task on shutdown."""
    global _session_manager_task
    if _session_manager_task is not None:
        _session_manager_task.cancel()
        try:
            await _session_manager_task
        except asyncio.CancelledError:
            pass
        _session_manager_task = None
        logger.info("MCP session manager stopped")
