"""Type definitions for External Plugin Guardrail Auditing and Migration Doctor Suite."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum


class PluginSafetyRating(StrEnum):
    """Automated security reputation tier for external plugins."""

    A_EXCELLENT = "A_EXCELLENT"
    B_GOOD = "B_GOOD"
    C_ELEVATED_RISK = "C_ELEVATED_RISK"
    F_UNTRUSTED = "F_UNTRUSTED"


class CapabilityScope(StrEnum):
    """Scoped execution permission capabilities declared by plugins."""

    NETWORK_EGRESS = "NETWORK_EGRESS"
    FILESYSTEM_READ = "FILESYSTEM_READ"
    FILESYSTEM_WRITE = "FILESYSTEM_WRITE"
    ENV_ACCESS = "ENV_ACCESS"
    PROCESS_SPAWN = "PROCESS_SPAWN"


@dataclass(slots=True, frozen=True)
class PluginManifest:
    """Plugin specification declared in plugin.json."""

    plugin_id: str
    name: str
    version: str
    author: str
    entrypoint: str
    declared_scopes: list[CapabilityScope] = field(default_factory=list)
    allowed_egress_hosts: list[str] = field(default_factory=list)
    required_env_keys: list[str] = field(default_factory=list)


@dataclass(slots=True, frozen=True)
class AuditFinding:
    """Specific vulnerability, undeclared capability, or AST violation discovered."""

    severity: str  # "INFO", "WARNING", "CRITICAL"
    rule_id: str
    description: str
    file_path: str | None = None
    line_number: int | None = None


@dataclass(slots=True, frozen=True)
class PluginAuditReport:
    """Consolidated safety rating and audit dossier."""

    plugin_id: str
    safety_rating: PluginSafetyRating
    is_install_allowed: bool
    findings: list[AuditFinding] = field(default_factory=list)
    scanned_files_count: int = 0
    audit_timestamp: float = 0.0


@dataclass(slots=True, frozen=True)
class MigrationDiagnosticItem:
    """Evaluation of a specific legacy state component."""

    target: str  # e.g. "plugin_config", "env_vars", "memory_vector_store"
    status: str  # "HEALTHY", "COMPATIBLE_NEEDS_UPGRADE", "CORRUPTED"
    details: str
    remediation_available: bool


@dataclass(slots=True, frozen=True)
class MigrationDoctorReport:
    """Complete diagnostic and auto-repair dossier generated by Migration Doctor."""

    is_migration_ready: bool
    diagnostics: list[MigrationDiagnosticItem] = field(default_factory=list)
    auto_remediated_count: int = 0
    notes: list[str] = field(default_factory=list)
