"""[POS]: src/myrm_agent_harness/toolkits/memory/reconciliation/models.py
[INPUT]: Dataclass primitives, StrEnum, datetime, and typing structures.
[OUTPUT]: Immutable models for reconciliation file metadata, reports, write-gate policies, and FTS search hits.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum


class WriteGatePolicy(StrEnum):
    """Explicit gate policies governing whether new persistent memory writes are permitted."""

    ENABLED = "enabled"
    READ_ONLY_SESSION = "read_only_session"
    DISABLED_TEMPORARY = "disabled_temporary"
    DISABLED_CONFIG_FAULT = "disabled_config_fault"


@dataclass(frozen=True)
class WriteGateCheckResult:
    """Outcome report evaluating whether a memory write is authorized."""

    is_allowed: bool
    policy: WriteGatePolicy
    reason: str


@dataclass
class DiskMemoryFileMeta:
    """Metadata tracking a physical markdown memory note file on disk."""

    file_path: str
    content_hash: str
    mtime: float
    title: str
    content: str
    indexed_at: datetime = field(default_factory=lambda: datetime.now(UTC))


@dataclass(frozen=True)
class ReconciliationReport:
    """Audit report generated by a bi-directional disk-memory FTS reconciliation loop."""

    reconcile_id: str
    scanned_disk_files_count: int
    indexed_or_updated_count: int
    pruned_dead_rows_count: int
    duration_ms: float
    status: str
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))


@dataclass(frozen=True)
class FtsReconciledHit:
    """Ranked search hit from reconciled FTS full-text virtual table."""

    file_path: str
    title: str
    snippet: str
    rank_score: float
