# [INPUT] None (Foundation domain types for decoupled memory consolidation and dreaming)
# [OUTPUT] MemoryDriveSpec, MemoryLogEntry, ConsolidatedEntityConcept, GoldenMemorySnapshot, DreamingConsolidationReport, SnapshotBroadcastNotification
# [POS] Domain data structures for detached memory drives, nightly dreaming pipelines, and cross-sandbox state synchronization

"""Type definitions for decoupled memory consolidation and dreaming state sync."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

StorageEngineType = Literal["sqlite", "json_lines", "duckdb_stub"]

MemoryEntryRole = Literal["user", "assistant", "system", "tool", "observation"]


@dataclass(frozen=True)
class MemoryDriveSpec:
    """Specification of an external detached memory storage drive."""

    drive_id: str
    mount_path: str
    storage_engine: StorageEngineType = "json_lines"
    max_capacity_bytes: int = 1024 * 1024 * 500  # 500 MB default
    current_usage_bytes: int = 0
    read_only: bool = False
    metadata: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True)
class MemoryLogEntry:
    """An atomic episodic interaction or fact log entry recorded in the drive."""

    entry_id: str
    session_id: str
    timestamp_unix: float
    role: MemoryEntryRole
    content: str
    category: str = "general"
    importance_score: float = 0.5  # 0.0 - 1.0
    access_count: int = 0
    tags: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class ConsolidatedEntityConcept:
    """A refined golden concept or entity distilled during nightly dreaming."""

    concept_id: str
    canonical_name: str
    aliases: list[str] = field(default_factory=list)
    attributes: dict[str, str] = field(default_factory=dict)
    confidence: float = 0.8
    source_entry_ids: list[str] = field(default_factory=list)
    last_reinforced_unix: float = 0.0


@dataclass(frozen=True)
class GoldenMemorySnapshot:
    """An immutable golden memory snapshot generated by the dreaming pipeline."""

    snapshot_id: str
    version: int
    timestamp_unix: float
    drive_id: str
    concepts: list[ConsolidatedEntityConcept]
    checksum_sha256: str
    total_entries_compacted: int = 0


@dataclass(frozen=True)
class DreamingConsolidationReport:
    """Audit report produced by the nightly dreaming and distillation pipeline."""

    dream_id: str
    start_time_unix: float
    duration_ms: float
    scanned_entries: int
    consolidated_concepts: int
    pruned_stale_entries: int
    compacted_bytes_saved: int
    vector_clusters_optimized: int
    snapshot_version: int
    success: bool
    summary: str


@dataclass(frozen=True)
class SnapshotBroadcastNotification:
    """A lightweight broadcast message informing active sandboxes of a new golden snapshot."""

    broadcast_id: str
    snapshot_id: str
    version: int
    drive_id: str
    checksum_sha256: str
    timestamp_unix: float
    target_sandbox_ids: list[str] = field(default_factory=list)
    ack_count: int = 0
