"""Context management module.

提供上下文过滤、压缩、摘要等功能，用于管理 Agent 的上下文窗口。

核心组件：
1. schemas: 紧凑格式和摘要模式定义
2. filter: 大型工具结果过滤（任务感知的混合过滤策略）
   - 结构化数据（JSON/XML/代码）：使用 StructuralFilter
   - 非结构化数据（HTML/Markdown/纯文本）：使用 SemanticFilter + LLM
3. compactor: 统一压缩逻辑（合并 Context Editing + Compact）
4. summarizer: 上下文摘要逻辑（最后手段）
5. filters: 过滤器子模块
   - StructuralFilter: 结构化数据过滤器
   - SemanticFilter: 语义过滤器（使用 LLM）
6. pipeline: Pipeline 架构的上下文处理
   - ContextPipeline: 管道引擎
   - 统一 builder: build_default_processors / create_default_pipeline
   - 处理器: ThinkingBlockCleaner, FilterProcessor, CompressProcessor,
     SessionNotesProcessor, SummarizeProcessor, ExplicitCacheProcessor

设计理念（来自 Manus + Anthropic）：
- 过滤 (Filtering) 是立即的：大结果截断 + 智能预览
- 压缩 (Compression)：三级策略（Dedup/Truncate/Remove）；通过 ContextCompressOffloadCallback 落盘后再紧凑化（Manus "有损但可追溯"原则）
  - 工具特定模板（保留标识符和元信息）
  - 最小清理保护（避免小清理破坏 Prompt Cache）
- 摘要 (Summarization) 是不可逆的：原始消息结构被替换，无法恢复
- 保留最近 N 次工具调用的完整格式，作为 few-shot 示例
"""

from .context import AgentContext
from .infra.archive_reference import ContextArchiveReference
from .infra.cache_policy import CacheTtlPrunePolicy, resolve_cache_ttl_prune_policy
from .infra.schemas import (
    BUILTIN_PROTECTED_TOOLS,
    DEFAULT_BUSINESS_PROTECTED_TOOLS,
    DEFAULT_CONTEXT_CONFIG,
    DEFAULT_SOFT_ONLY_TOOLS,
    TOOL_PROTECTION_CONFIG,
    CacheUsageFeedback,
    CompactToolCall,
    CompressionIntent,
    ContextCompressOffloadCallback,
    ContextConfig,
    ContextOffloadResult,
    ContextSnapshotCallback,
    StructuredSummary,
    ToolProtectionConfig,
    ToolPruneMode,
)
from .infra.session_lock import (
    acquire_context_lock,
    clear_all_locks,
    get_active_session_count,
    get_current_chat_id,
    get_locked_session_count,
    get_session_lock,
    reset_current_chat_id,
    set_current_chat_id,
)

# Pipeline 架构
from .pipeline import (
    BaseProcessor,
    CompressProcessor,
    ContextPipeline,
    ExplicitCacheProcessor,
    FilterProcessor,
    ProcessorContext,
    ReasoningAnchorProcessor,
    SessionNotesProcessor,
    SummarizeProcessor,
    ThinkingBlockCleaner,
    build_default_processors,
    create_default_pipeline,
)
from .strategies.compactor import (
    COMPACT_RULES,
    compress_messages_async,
    compress_tool_message_async,
)
from .strategies.filter import (
    FILTER_TOKEN_THRESHOLD,
    FilteredResult,
    create_filtered_result,
    format_filtered_message,
    should_filter,
)
from .strategies.filters import BaseFilter, FilterContext, FilterResult, SemanticFilter, StructuralFilter
from .strategies.filters.base import SEMANTIC_CONTENT_TYPES, STRUCTURAL_CONTENT_TYPES, detect_content_type
from .strategies.summary.summarizer import generate_structured_summary, should_summarize
from .tracking.artifact_tracker import (
    ArtifactAction,
    ArtifactRecord,
    ArtifactTracker,
    clear_artifact_tracker,
    create_artifact_tracker,
    get_all_active_trackers,
    get_artifact_tracker,
    get_or_create_artifact_tracker,
)
from .tracking.task_metrics import (
    ArchiveRestoreBlockEvent,
    CompressionEvent,
    RefetchEvent,
    TaskMetrics,
    clear_task_metrics,
    create_task_metrics,
    get_all_active_metrics,
    get_or_create_task_metrics,
    get_task_metrics,
    record_archive_refetch_for_path,
)
from .active_compression import (
    ActiveCompressionConfig,
    ActiveCompressionResult,
    ActiveContextCompressionEngine,
    CompressTriggerKind,
    TokenPressureGauge,
    TokenPressureLevel,
    TokenPressureSnapshot,
)
from .ambiguity_probe import (
    AmbiguityClarificationProbe,
    AmbiguityLevel,
    BacktrackedContextDossier,
    ClarificationProbeResult,
    ClarificationQuestion,
    EntityGraphMatch,
)
from .canvas_deeplink import (
    CanvasAssetRegistry,
    CanvasDeepLinkParser,
    CanvasDeepLinkUri,
    CanvasDesignAsset,
    CanvasDesignTokens,
    CanvasLayerKind,
    CanvasLayerNode,
    CanvasTunnelingEngine,
    ProStudioPlatform,
    ProStudioSyncPayload,
)
from .clean_pod_archival import (
    CleanPodArchivalConfig,
    CleanPodArchivalEngine,
    EphemeralCleanPodDescriptor,
    NightlyArchivalJob,
    NightlyArchivalStatus,
    PodLifecycleState,
    TaskDeliverableContract,
)
from .context_diet import (
    ComponentTokenAuditItem,
    ContextComponentKind,
    ContextDietBudgetBill,
    ContextDietConfig,
    ContextDietEngine,
    DistilledSkillCard,
)
from .demand_hydration import (
    DemandHydrationConfig,
    HydratedContextEnvelope,
    HydrationDecision,
    HydrationTriggerMode,
    OnDemandContextHydrator,
    ProfileCardCategory,
    UserMemoryCard,
)
from .branch_summary import (
    BranchFileOperations,
    BranchFileOperationsTracker,
    BranchMergeConflictWarning,
    BranchSelectiveMergeEngine,
    BranchSummaryResult,
    FileActionKind,
    SelectiveMergePolicy,
    TrackedFileOperation,
)
from .dual_branching import (
    BranchDescriptor,
    BranchingPosture,
    DualBranchingSessionEngine,
    ForkCloneResult,
    TreeNodeMessage,
    VersionNavigationInfo,
)
from .dual_loop_steering import (
    DualLoopQueueSnapshot,
    DualLoopSessionQueueLedger,
    InnerLoopSteeringInterceptor,
    KeyStrokeIntent,
    LoopSteeringKind,
    SteeringDirective,
    SteeringDirectiveStatus,
)
from .dual_track_interjection import (
    DualTrackInterventionConfig,
    DualTrackInterventionCoordinator,
    InterventionStatus,
    InterventionTrack,
    PreemptionQueueSnapshot,
    StepBoundaryInjectionResult,
    UserInterventionDirective,
)
from .emergent_attention import (
    ActionTraceEvent,
    EmergentAttentionDossier,
    EmergentAttentionEngine,
    EmergentAttentionItem,
    InboundNotification,
    IntentionActionDiffItem,
    IntentionActionDiffReport,
    NotificationSieveResult,
    SieveDecision,
    StatedIntention,
    UserActionTraceKind,
)
from .harness_tax import (
    CompactWorkingMemoryProjector,
    CompactWorkingMemoryView,
    HarnessTaxAuditReport,
    HarnessTaxConfig,
    ResourceLoadBundle,
    ToolDescriptor,
    ToolExposurePolicy,
)
from .inbound_shield import (
    InboundMessageOverflowShield,
    InboundMountedDocument,
    InboundPayloadClassification,
    InboundShieldConfig,
    InboundShieldResult,
)
from .million_token_ceiling import (
    CompactionTierAction,
    CompactionTrackType,
    ContextBudgetForecast,
    MillionTokenCeilingConfig,
    MillionTokenCompactionResult,
    MillionTokenCeilingGovernor,
    OffloadedToolArtifact,
)
from .multibot_governor import (
    BotTurnEvent,
    CognitiveValueEvaluation,
    GovernorAction,
    GovernorDecision,
    GroupTurnArbitrator,
    IncrementalCognitiveValueEvaluator,
    MessageSenderRole,
    MultiBotChatterGovernor,
    MultiBotGovernorConfig,
    MutexAcquireResult,
)
from .owner_fencing import (
    AdmissionDecision,
    AdmissionStatus,
    DurableSessionOwnerFencer,
    FencingConfig,
    SessionOwnerLease,
    SessionQuiesceState,
)
from .privacy_mode import (
    ConversationPrivacyGateEngine,
    PrivacyBoundToolSet,
    PrivacyModeLevel,
    PrivacyModeSessionConfig,
    ToolCallInterceptRecord,
    ToolHardGateAction,
)
from .project_container import (
    DragDropIngestionEvent,
    ProjectAssetItem,
    ProjectAssetKind,
    ProjectContainerWorkspace,
    SessionVisibilityStatus,
    SilentArchivingResult,
    UnifiedProjectContainerEngine,
)
from .rule_lifecycle import (
    AgentRuleLifecycleAuditor,
    RuleAuditItem,
    RuleConflictPair,
    RuleConflictType,
    RuleLifecycleConfig,
    RuleLifecycleReport,
    RuleLifecycleState,
)
from .session_commit import (
    CommitJobStatus,
    CommitTriggerReason,
    ExperienceLearningItem,
    Phase1SnapshotResult,
    ProjectGuidelineItem,
    SessionCommitJob,
    SessionCommitPolicyConfig,
    TriDimensionalDistillationResult,
    TwoPhaseSessionCommitEngine,
    UserPreferenceItem,
)
from .session_dom import (
    RewindLifecycleAction,
    RewindLifecycleWorklist,
    SessionDomNode,
    SessionDomNodeKind,
    SessionDomPatch,
    SessionDomPatchOp,
    SessionDomTree,
    UniversalEventSourcedSessionDomEngine,
)
from .session_roaming import (
    CollaborationRole,
    DeviceAgnosticSessionRoamingEngine,
    DevicePlatform,
    ExecutableTeamShareBundle,
    ForkAndContinueResult,
    SandboxWarmMirrorSpec,
    SessionRoamingBreakpoint,
)
from .shareable_fork import (
    InteractiveShareableForkEngine,
    LosslessForkResult,
    ShareAccessPermission,
    ShareTokenPayload,
    ShareableForkConfig,
    SharedSessionPerspective,
)
from .worktree_isolation import (
    SessionWorktreeBinding,
    WorktreeDescriptor,
    WorktreeHygieneReport,
    WorktreeHygieneStatus,
    WorktreeRemovalPolicy,
    WorktreeRemovalResult,
    WorktreeSessionIsolationEngine,
)
from .working_memory import (
    LocalWorkingMemoryBlock,
    LocalWorkingState,
    SubtaskItem,
    SubtaskStatus,
    TrapRecord,
)
from .workspace_guard import (
    ExplorationDecisionStatus,
    ExplorationGuardDecision,
    PromptCrawlSuppressionFilter,
    WorkspaceAccessPolicy,
    WorkspaceExplorationGuardEngine,
    WorkspaceGuardConfig,
)
from .subagent_scratchpad import (
    EphemeralSubagentDossier,
    FactCategory,
    MultiAgentSharedScratchpadEngine,
    ScratchpadQueryFilter,
    SharedScratchpadFact,
    SubagentLifecycleStatus,
)
from .visual_pruner import (
    PrunedFrameFootprint,
    VisualFramePruningEngine,
    VisualPruningConfig,
    VisualPruningMode,
    VisualPruningResult,
)
from .desktop_repl import (
    DesktopApiSdk,
    DesktopElementMock,
    DesktopReplSessionSnapshot,
    PersistentDesktopReplEngine,
    ReplExecutionResult,
    ReplExecutionStatus,
    ReplRuntimeKind,
    ReplScriptCommand,
)
from .turn_truncation import (
    CanonicalTurnCommit,
    IntermediateTrialKind,
    PrefixCacheStabilityReport,
    TrialStepRecord,
    TruncationPolicy,
    TurnExecutionState,
    TurnStateTruncationEngine,
)
from .revocation_eviction import (
    RevocationDirective,
    RevocationEvictionEngine,
    RevocationScopeKind,
    SanitizationOutcome,
    TaintedContentBlock,
)
from .midflight_steering import (
    MidFlightDirective,
    MidFlightSteeringCoordinator,
    SteeringDirectiveStatus,
    SteeringExecutionTelemetry,
    SteeringInjectionEnvelope,
    SteeringIntentKind,
)
from .session_search import (
    SearchRoleFilter,
    SessionHistoryFTS5SearchEngine,
    SessionSearchHit,
    SessionSearchQuery,
    SessionSearchResult,
    SessionSearchScope,
)
from .context_pivot import (
    ArchivedContextSnapshot,
    ContextPivotConfig,
    ContextPivotResult,
    HandoffScratchpad,
    LosslessContextPivotEngine,
    PivotTriggerKind,
)
from .proactive_recall import (
    ContextGapAutoProbeEngine,
    ContextGapDetection,
    EntityType,
    PrunedEntityRecord,
    ProactiveRecallNudgeConfig,
    ProactiveRecallProbeResult,
)
from .session_bridge import (
    BridgeMessageItem,
    ExportBridgeResult,
    ExternalHarnessFormat,
    FullStateHandoffBundle,
    SessionWorkspaceState,
    ToolExecutionTrace,
    UniversalSessionBridgeEngine,
    UniversalSessionDescriptor,
)
from .skill_immunity import (
    ActiveSkillImmunityEngine,
    ActiveSkillSpec,
    ReAnchorAnchorPosition,
    ReAnchorOutcome,
    SkillImmunityConfig,
    SkillImmunityScope,
)
from .mvp_distiller import (
    ComplexProjectMvpDistillerEngine,
    DistillationOutcome,
    ModuleSpec,
    MvpDistillerConfig,
    MvpPhaseLifecycleState,
    PhaseScopePlan,
    ProjectComplexityLevel,
)
from .cron_mirroring import (
    ContinuableCronSessionMirrorEngine,
    ContinuableJobSpec,
    CronDeliveryRecord,
    CronMirrorConfig,
    CronMirrorRoleMode,
    CronMirroringOutcome,
)
from .ipc_clamping import (
    IpcClampingAction,
    IpcClampingConfig,
    IpcClampingOutcome,
    IpcMessageClampingAndSpilloverEngine,
    SpilloverArtifactSpec,
)
from .dual_file_decoupling import (
    DualFileContextEnvelope,
    DualFileDecouplingConfig,
    DualFileProjectContextDecouplingEngine,
    DynamicOverviewSections,
    ProjectRuleInvariantSpec,
)
from .project_handoff import (
    HandoffHandshakeResponse,
    ProjectHandoffConfig,
    ProjectHandoffStatus,
    ProjectWorkspaceDossier,
    TenSecondProjectHandoffEngine,
)
from .live_steering import (
    LiveResponseSteeringEngine,
    LiveSteerStatus,
    LiveSteeringConfig,
    LiveSteeringInjectionResult,
    LiveSteeringInstruction,
    LiveSteeringReconciledHistory,
    SteerChannelMode,
    SteerSeverity,
    ToolSeamAnchor,
)
from .token_governor import (
    BurnRateTelemetry,
    BurnRateZone,
    LeanToolPruningDecision,
    RateLimitBackoffDecision,
    TokenBurnRateGovernorEngine,
    TokenGovernorConfig,
    TokenUsageRecord,
    ToolLeanMode,
)
from .sandbox_reduction import (
    ActionKind,
    ActionLedgerEntry,
    InSandboxDataReductionEngine,
    LedgerQueryResult,
    ReducedOutputEnvelope,
    ReductionKind,
    SandboxReductionConfig,
)
from .prompt_cache_clock import (
    CacheTierKind,
    ClockBucketResolution,
    ContextClockSpec,
    PromptCacheClockConfig,
    PromptCacheClockGovernorEngine,
    PromptCacheTierBlock,
    TieredAssemblyResult,
    ToolChoiceMode,
)
from .fallback_buffer_notebook import (
    BufferWatermarkSnapshot,
    BufferWatermarkState,
    CompactionConsequenceAlert,
    FallbackBufferConfig,
    FallbackBufferNotebookEngine,
    TeamNotebookEntry,
    TeamNotebookSnapshot,
)
from .migratable_session import (
    DecoupledMigratableSessionEngine,
    MigratableSessionBundle,
    MigratableSessionConfig,
    SessionAccessRole,
    SessionForkOutcome,
    SessionLiveStatus,
    SessionLocationKind,
    SessionShareGrant,
    WorkspaceHotSeedSpec,
)
from .session_antidote import (
    AntidoteReceipt,
    ConfigDriftDetail,
    ConfigMutationProposal,
    FlagScope,
    GenesisConfigSnapshot,
    PoisonDiagnosisReport,
    PoisonSeverity,
    SessionAntiPoisoningEngine,
    SessionAntidoteConfig,
)
from .reasoning_collapse import (
    ReasoningCollapseConfig,
    ReasoningCollapseReport,
    ReasoningStreamCollapseEngine,
    ReasoningVendorType,
    ThinkingCollapseMode,
    UnifiedReasoningBlock,
)
from .progressive_disclosure import (
    AttributionValidationResult,
    CognitiveMilestoneFact,
    DisclosureStage,
    EvidenceAttributionType,
    EvidenceCitation,
    ProgressiveDisclosureConfig,
    ProgressiveDisclosureEngine,
)
from .tool_paging import (
    ModelNativeToolPagingEngine,
    ModelTier,
    PageInSlice,
    ToolBlobRecord,
    ToolOutputStub,
    ToolPagingConfig,
    ToolSchemaDefinition,
)
from .token_efficiency import (
    NegativeRouteDecision,
    NegativeRouteRule,
    ProviderUsageAnchor,
    ReasoningSealBlock,
    TokenEfficiencyConfig,
    TokenEfficiencyGovernorEngine,
    TokenEfficiencyLedger,
)
from .hysteresis_compression import (
    CooldownStatus,
    HysteresisCompressionEngine,
    HysteresisConfig,
    HysteresisEvaluation,
    HysteresisExecutionReport,
    SanctuaryBlock,
    SanctuaryCategory,
    WatermarkTier,
)
from .cloud_snapshot import (
    CloudSnapshotConfig,
    IncrementalPatchBundle,
    InstantCloudSnapshotRestoreEngine,
    SandboxPoolState,
    SnapshotRestoreResult,
    SnapshotStorageDriver,
    VolumeSnapshotDescriptor,
    WarmSandboxDescriptor,
)
from .sandbox_interceptor import (
    ContextHookStage,
    InterceptedToolOutput,
    LifecycleHookRecord,
    SandboxInterceptorConfig,
    SandboxOutputInterceptorEngine,
    SearchResultSnippet,
    ToolOutputStub,
)
from .barge_in_steering import (
    BargeInMessage,
    BargeInSteeringConfig,
    InterventionMode,
    InterventionStatus,
    MidRunBargeInSteeringEngine,
    SteeringPointGateResult,
)
from .clean_markdown_extractor import (
    CleanMarkdownExtractorConfig,
    CleanMarkdownExtractorEngine,
    DOMPruneRule,
    ExtractedCleanContent,
    ExtractionDensityLevel,
    SparsityPruneResult,
)
from .sandplay_simulation import (
    CausalityEdge,
    CausalityNode,
    CausalityTier,
    FinancialSandplaySimulationEngine,
    ImpactDirection,
    IndustryChainGraph,
    SandplaySimulationResult,
    SolidifiedSkillPackage,
)
from .branch_projection import (
    BranchSummary,
    DualTrackBranchProjectionEngine,
    EntryKind,
    OperationStatus,
    ProjectedContext,
    SessionEntry,
    SessionOperation,
    TokenUsage,
    collect_departed_entries,
    find_lca,
    synthesize_branch_delta_summary,
)
from .browser_batch_script import (
    ArtifactFormatKind,
    BatchExecutionResult,
    BatchExtractionIntent,
    BatchFieldSpec,
    BrowserBatchProcessingEngine,
    DashboardMetricCard,
    InteractiveDashboardSpec,
    PaginationStrategy,
    SynthesizedBrowserScript,
    synthesize_batch_crawling_script,
)
from .tool_safe_compaction import (
    CutPointEvaluation,
    CutPointSafetyKind,
    FileManifests,
    MessageRole,
    SafeCompactionResult,
    ToolSafeCompactionEngine,
    evaluate_cut_point,
    extract_file_manifests,
    find_valid_cut_points,
    select_optimal_safe_cut_point,
)
from .mention_hydration import (
    HydratedTurnPayload,
    MentionHydrationConfig,
    MentionHydrationEngine,
    MentionKind,
    ParsedMention,
    PreHydratedAttachment,
    compute_content_hash,
    parse_mentions_from_prompt,
)
from .cache_shield import (
    CacheBreakEvaluation,
    CacheBreakPreventionShieldEngine,
    CacheParameterKind,
    CachePreservingForkResult,
    CacheRewindResult,
    CacheRiskLevel,
    evaluate_parameter_mutation,
)
from .command_quiet_rewriter import (
    CommandQuietRewriterAndLogSinkSuite,
    LogSinkConclusionCard,
    LogSinkStatus,
    LogSinkTaskSpec,
    LogSinkTaskType,
    PreflightCommandRewriter,
    QuietRewriteRule,
    RewriteResult,
    RewriteStatus,
    SubagentLogSinkEngine,
    SubagentLogSinkExecutionRecord,
)
from .cold_start_profiler import (
    ColdStartContextProfile,
    ColdStartContextProfilerAndOnDemandMcpMountSuite,
    ColdStartContextProfilerEngine,
    ContextComponentKind,
    ContextComponentProfile,
    McpMountMutationResult,
    McpServerDescriptor,
    McpServerMountState,
    OnDemandMcpMountManager,
)
from .custom_compaction_directives import (
    CompactionDirectivesInjector,
    CompactionIntegrityReport,
    CustomCompactionConfig,
    CustomCompactionDirectivesAndPreservationWhitelistSuite,
    DirectiveAuditResult,
    PreservationDirective,
    PreservationDirectiveKind,
    PreservationWhitelistAuditor,
)
from .zero_thinking_route import (
    DeterministicTaskDetection,
    DeterministicTaskDetector,
    ModelProviderKind,
    ProviderThinkingPayload,
    ThinkingBudgetMode,
    ThinkingParameterNormalizer,
    ZeroThinkingBudgetDirectRouteSuite,
    ZeroThinkingSavingsRecord,
)
from .smart_idle_compactor import (
    CacheWindowStatus,
    CompactedCheckpointArchive,
    IdleCompactionAction,
    IdleCompactionEvaluation,
    IdleCompactorConfig,
    IdleEligibilityEvaluator,
    OpportunisticCompactorEngine,
    OpportunisticCompactionResult,
    SmartIdleCachePreservingAutoCompactorSuite,
    ZeroWaitWakeupEvent,
)
from .topic_drift_fork import (
    DriftSignalKind,
    ForkExecutionResult,
    SessionForkManager,
    SessionForkSuggestion,
    TopicDriftDemarcationAndAutoRenamedSessionForkSuite,
    TopicDriftDetector,
    TopicDriftEvaluation,
)
from .portable_export import (
    AgentOwnershipPortableExportAndNoLockInSuite,
    ContextArtifactKind,
    ExportIntegrityReceipt,
    ExportScope,
    PortableBundleBuilder,
    PortableContextBundle,
    PortableContextItem,
)
from .checked_stream_reader import (
    AntiSlopFilter,
    AntiSlopFilterResult,
    AntiSlopViolationKind,
    CheckedSessionReplyStreamReader,
    CheckedSessionReplyStreamReadersAndAntiSlopGovernanceSuite,
    StreamChunkFrame,
    StreamChunkKind,
    StreamReaderMetrics,
    StreamReaderState,
)
from .multimodal_budget import (
    GuardianReviewResult,
    GuardianVerdictKind,
    ImageArtifactDescriptor,
    ImageBudgetAction,
    ImageBudgetAllocation,
    ImageDetailMode,
    ImageResolution,
    ImageTokenBudgetCalculator,
    MultiModalBudgetReport,
    MultiModalFileImageContextBudgetAndGuardianReviewSuite,
    MultiModalGuardianReviewer,
)
from .resumed_usage_meter import (
    NetRunUsage,
    NetRunUsageMeter,
    RawTurnUsage,
    ResumedSessionHistoryTokenExclusionAndNetRunUsageMeterSuite,
    ResumptionBaseline,
    SessionUsageSummary,
    UsageBillingLedgerRecord,
)
from .devflow_lifecycle import (
    ContextAdmissionDecision,
    ContextGateEvaluator,
    DevFlowContextLifecycleAndProgressiveLoadingSuite,
    DevFlowPhase,
    ExplorationHandoffEngine,
    GateQuestionnaireEvaluation,
    PhaseLifecycleState,
    StructuredExplorationHandoff,
)
from .headless_continuation import (
    ApprovalDecisionKind,
    ApprovalRelayReceipt,
    ClientAttachmentState,
    HeadlessContinuationSuite,
    HeadlessExecutionPhase,
    MobileApprovalDecisionPayload,
    MobileApprovalRelayCard,
    MobileApprovalRelayEngine,
    ReconnectionSyncManifest,
    RelayChannelKind,
    RiskLevel,
)
from .session_handoff import (
    HandoffMessageTurn,
    LineBlameEntry,
    LineBlameLookupResult,
    ReadonlyShareGrant,
    SecretFinding,
    SecretGateScanResult,
    SecretGateScanner,
    SecretSeverity,
    SessionBlameIndexer,
    SessionHandoffPackage,
    SessionHandoffPackageAndReadonlyShareAndSecretGateAndBlameSuite,
    ShareAccessStatus,
)
from .layered_loop_termination import (
    DebtInboxItem,
    DebtInboxManager,
    DebtKind,
    LayeredLoopEvent,
    LayeredLoopTerminationAndDebtInboxSuite,
    LoopHierarchyTier,
    LoopTerminationDecision,
    LoopTerminationReason,
)
from .single_tier_override import (
    OverrideResolutionKind,
    RuleLayerKind,
    SingleTierRuleAssemblyReceipt,
    SingleTierRuleResolver,
    SingleTierWorkspaceRuleOverrideInterceptorSuite,
    WorkspaceRuleFileEntry,
)
from .system_append_channel import (
    AppendPromptSource,
    PromptChannelKind,
    SystemPromptAppendLoader,
    SystemPromptAssemblyReceipt,
    SystemPromptStrongAppendChannelSuite,
)
from .cross_ecosystem_migration import (
    CrossEcosystemRuleMigrationAndCompatibilityInspectorSuite,
    CrossEcosystemRuleScanner,
    CrossEcosystemTranspiler,
    DiscoveredEcosystemFile,
    EcosystemConflictItem,
    EcosystemSpecKind,
    RuleMigrationReportReceipt,
    RuleSectionCategory,
)
from .event_sourcing_replayer import (
    AppendOnlyEventLog,
    AppendOnlySessionEventSourcingAndContextReplayerSuite,
    ContextReplayCertificate,
    DeterministicContextProjector,
    ProjectedMessageItem,
    ProjectedModelVisibleContext,
    SessionEventKind,
    SessionLedgerEvent,
)
from .session_tree_dag import (
    DagEntryKind,
    SessionBranchMeta,
    SessionTreeDagReceipt,
    SessionTreeDagSuite,
    SessionTreeEntry,
    SessionTreeStorage,
)
from .dual_mode_compaction import (
    CompactableMessage,
    CompactionExecutionResult,
    CompactionTriggerKind,
    ContextWindowBudgetConfig,
    DualModeCompactionAndOverflowSelfHealingSuite,
    ProviderOverflowDetector,
    ProviderOverflowKind,
    SelfHealingAuditReceipt,
)
from .branch_switch_summarization import (
    BranchExplorationCard,
    BranchOutcomeCondenser,
    BranchOutcomeVerdict,
    BranchSummaryEntry,
    BranchSwitchSummarizationAndContextTransferSuite,
    BranchTransferReceipt,
)
from .two_stage_pipeline import (
    AssemblyAdjustmentDirective,
    LlmProviderProtocolKind,
    LogicalContextBundle,
    LogicalToolSpec,
    LogicalTurn,
    PipelineStageReceipt,
    ProviderPayloadResult,
    ProviderProtocolTranspiler,
    TwoStageContextPipelineAndProviderProtocolDecouplingSuite,
)
from .workspace_branch_stash import (
    BranchSwitchWorkspaceStashAndArtifactIntegritySuite,
    BranchWorkspaceSnapshot,
    FileStashKind,
    ShadowStashEngine,
    ShadowStashFileRecord,
    WorkspaceStashConflictWarning,
    WorkspaceStashReceipt,
)
from .transparent_gauge import (
    BudgetAnalyzer,
    BudgetSegmentBreakdown,
    BudgetSegmentKind,
    CompactionAdjustmentIntervention,
    ContextWindowTransparentGaugeAndBudgetBreakdownSuite,
    TransparentGaugeReceipt,
    WatermarkAlertLevel,
    WatermarkState,
)
from .session_tree_gc import (
    GcSafetyRule,
    PrunedBranchReport,
    SessionTreeBranchPruneAndStorageGCSuite,
    SessionTreeGcEngine,
    StorageGcReceipt,
)
from .table_protection import (
    HistoryAssistantTablePruneAndLastRoundProtectSuite,
    MarkdownTableBlock,
    MarkdownTableDetector,
    TableProtectionMode,
    TablePruningProtector,
    TablePruningReceipt,
)
from .session_pins import (
    PinActionKind,
    SessionDeeplinkRoute,
    SessionPinRepository,
    SessionPinState,
    SessionPinSyncReceipt,
    SessionPinsPersistedInSessionsSuite,
)
from .native_thread_history import (
    FallbackStatus,
    GuardValidationResult,
    LargeNativeThreadHistoryPreserveSuite,
    SortKeyFallbackGuard,
    SortKeyKind,
    ThreadEntry,
    ThreadHistoryPage,
    ThreadPageRequest,
)
from .spawn_reservation import (
    AdmissionCommitResult,
    ReservationResult,
    ReservationState,
    SpawnNameReservationEngine,
    SpawnNameReservationUntilAdmissionDurableSuite,
    SpawnReservationLease,
)
from .ask_only_mode import (
    AskOnlyFilterResult,
    AskOnlyToolFilter,
    SessionInteractionMode,
    ToolDescriptor,
    ToolExecutionCheckResult,
    ToolSideEffectLevel,
    WorkBuddyAskOnlyModeSuite,
)
from .handoff_checkpoint import (
    CheckpointRenderFormat,
    HandoffCompactStage,
    HandoffCheckpointCompiler,
    HandoffThenCompactResult,
    TaskCheckpoint,
    WorkBuddyHandoffThenCompactSuite,
)
from .sandbox_pause_resume import (
    AgentkitPauseResumeSessionSandboxSuite,
    PauseResumeActionKind,
    PauseResumeReceipt,
    SandboxPauseResumeEngine,
    SandboxSessionRecord,
    SandboxSnapshotManifest,
    SessionLifecycleState,
    compute_state_checksum,
)
from .stale_query_expire import (
    ContextEvaluationResult,
    MateclawStaleQueryContextExpireSuite,
    QueryContextStatus,
    QueryIntentEntry,
    StaleQueryExpiryEngine,
)

__all__ = [
    # sandbox_pause_resume
    "AgentkitPauseResumeSessionSandboxSuite",
    "PauseResumeActionKind",
    "PauseResumeReceipt",
    "SandboxPauseResumeEngine",
    "SandboxSessionRecord",
    "SandboxSnapshotManifest",
    "SessionLifecycleState",
    "compute_state_checksum",
    # stale_query_expire
    "ContextEvaluationResult",
    "MateclawStaleQueryContextExpireSuite",
    "QueryContextStatus",
    "QueryIntentEntry",
    "StaleQueryExpiryEngine",
    # handoff_checkpoint
    "CheckpointRenderFormat",
    "HandoffCompactStage",
    "HandoffCheckpointCompiler",
    "HandoffThenCompactResult",
    "TaskCheckpoint",
    "WorkBuddyHandoffThenCompactSuite",
    # ask_only_mode
    "AskOnlyFilterResult",
    "AskOnlyToolFilter",
    "SessionInteractionMode",
    "ToolDescriptor",
    "ToolExecutionCheckResult",
    "ToolSideEffectLevel",
    "WorkBuddyAskOnlyModeSuite",
    # spawn_reservation
    "AdmissionCommitResult",
    "ReservationResult",
    "ReservationState",
    "SpawnNameReservationEngine",
    "SpawnNameReservationUntilAdmissionDurableSuite",
    "SpawnReservationLease",
    # native_thread_history
    "FallbackStatus",
    "GuardValidationResult",
    "LargeNativeThreadHistoryPreserveSuite",
    "SortKeyFallbackGuard",
    "SortKeyKind",
    "ThreadEntry",
    "ThreadHistoryPage",
    "ThreadPageRequest",
    # session_pins
    "PinActionKind",
    "SessionDeeplinkRoute",
    "SessionPinRepository",
    "SessionPinState",
    "SessionPinSyncReceipt",
    "SessionPinsPersistedInSessionsSuite",
    # table_protection
    "HistoryAssistantTablePruneAndLastRoundProtectSuite",
    "MarkdownTableBlock",
    "MarkdownTableDetector",
    "TableProtectionMode",
    "TablePruningProtector",
    "TablePruningReceipt",
    # session_tree_gc
    "GcSafetyRule",
    "PrunedBranchReport",
    "SessionTreeBranchPruneAndStorageGCSuite",
    "SessionTreeGcEngine",
    "StorageGcReceipt",
    # transparent_gauge
    "BudgetAnalyzer",
    "BudgetSegmentBreakdown",
    "BudgetSegmentKind",
    "CompactionAdjustmentIntervention",
    "ContextWindowTransparentGaugeAndBudgetBreakdownSuite",
    "TransparentGaugeReceipt",
    "WatermarkAlertLevel",
    "WatermarkState",
    # workspace_branch_stash
    "BranchSwitchWorkspaceStashAndArtifactIntegritySuite",
    "BranchWorkspaceSnapshot",
    "FileStashKind",
    "ShadowStashEngine",
    "ShadowStashFileRecord",
    "WorkspaceStashConflictWarning",
    "WorkspaceStashReceipt",
    # two_stage_pipeline
    "AssemblyAdjustmentDirective",
    "LlmProviderProtocolKind",
    "LogicalContextBundle",
    "LogicalToolSpec",
    "LogicalTurn",
    "PipelineStageReceipt",
    "ProviderPayloadResult",
    "ProviderProtocolTranspiler",
    "TwoStageContextPipelineAndProviderProtocolDecouplingSuite",
    # branch_switch_summarization
    "BranchExplorationCard",
    "BranchOutcomeCondenser",
    "BranchOutcomeVerdict",
    "BranchSummaryEntry",
    "BranchSwitchSummarizationAndContextTransferSuite",
    "BranchTransferReceipt",
    # dual_mode_compaction
    "CompactableMessage",
    "CompactionExecutionResult",
    "CompactionTriggerKind",
    "ContextWindowBudgetConfig",
    "DualModeCompactionAndOverflowSelfHealingSuite",
    "ProviderOverflowDetector",
    "ProviderOverflowKind",
    "SelfHealingAuditReceipt",
    # session_tree_dag
    "DagEntryKind",
    "SessionBranchMeta",
    "SessionTreeDagReceipt",
    "SessionTreeDagSuite",
    "SessionTreeEntry",
    "SessionTreeStorage",
    # event_sourcing_replayer
    "AppendOnlyEventLog",
    "AppendOnlySessionEventSourcingAndContextReplayerSuite",
    "ContextReplayCertificate",
    "DeterministicContextProjector",
    "ProjectedMessageItem",
    "ProjectedModelVisibleContext",
    "SessionEventKind",
    "SessionLedgerEvent",
    # cross_ecosystem_migration
    "CrossEcosystemRuleMigrationAndCompatibilityInspectorSuite",
    "CrossEcosystemRuleScanner",
    "CrossEcosystemTranspiler",
    "DiscoveredEcosystemFile",
    "EcosystemConflictItem",
    "EcosystemSpecKind",
    "RuleMigrationReportReceipt",
    "RuleSectionCategory",
    # system_append_channel
    "AppendPromptSource",
    "PromptChannelKind",
    "SystemPromptAppendLoader",
    "SystemPromptAssemblyReceipt",
    "SystemPromptStrongAppendChannelSuite",
    # single_tier_override
    "OverrideResolutionKind",
    "RuleLayerKind",
    "SingleTierRuleAssemblyReceipt",
    "SingleTierRuleResolver",
    "SingleTierWorkspaceRuleOverrideInterceptorSuite",
    "WorkspaceRuleFileEntry",
    # layered_loop_termination
    "DebtInboxItem",
    "DebtInboxManager",
    "DebtKind",
    "LayeredLoopEvent",
    "LayeredLoopTerminationAndDebtInboxSuite",
    "LoopHierarchyTier",
    "LoopTerminationDecision",
    "LoopTerminationReason",
    # session_handoff
    "HandoffMessageTurn",
    "LineBlameEntry",
    "LineBlameLookupResult",
    "ReadonlyShareGrant",
    "SecretFinding",
    "SecretGateScanResult",
    "SecretGateScanner",
    "SecretSeverity",
    "SessionBlameIndexer",
    "SessionHandoffPackage",
    "SessionHandoffPackageAndReadonlyShareAndSecretGateAndBlameSuite",
    "ShareAccessStatus",
    # headless_continuation
    "ApprovalDecisionKind",
    "ApprovalRelayReceipt",
    "ClientAttachmentState",
    "HeadlessContinuationSuite",
    "HeadlessExecutionPhase",
    "MobileApprovalDecisionPayload",
    "MobileApprovalRelayCard",
    "MobileApprovalRelayEngine",
    "ReconnectionSyncManifest",
    "RelayChannelKind",
    "RiskLevel",
    # devflow_lifecycle
    "ContextAdmissionDecision",
    "ContextGateEvaluator",
    "DevFlowContextLifecycleAndProgressiveLoadingSuite",
    "DevFlowPhase",
    "ExplorationHandoffEngine",
    "GateQuestionnaireEvaluation",
    "PhaseLifecycleState",
    "StructuredExplorationHandoff",
    # resumed_usage_meter
    "NetRunUsage",
    "NetRunUsageMeter",
    "RawTurnUsage",
    "ResumedSessionHistoryTokenExclusionAndNetRunUsageMeterSuite",
    "ResumptionBaseline",
    "SessionUsageSummary",
    "UsageBillingLedgerRecord",
    # multimodal_budget
    "GuardianReviewResult",
    "GuardianVerdictKind",
    "ImageArtifactDescriptor",
    "ImageBudgetAction",
    "ImageBudgetAllocation",
    "ImageDetailMode",
    "ImageResolution",
    "ImageTokenBudgetCalculator",
    "MultiModalBudgetReport",
    "MultiModalFileImageContextBudgetAndGuardianReviewSuite",
    "MultiModalGuardianReviewer",
    # checked_stream_reader
    "AntiSlopFilter",
    "AntiSlopFilterResult",
    "AntiSlopViolationKind",
    "CheckedSessionReplyStreamReader",
    "CheckedSessionReplyStreamReadersAndAntiSlopGovernanceSuite",
    "StreamChunkFrame",
    "StreamChunkKind",
    "StreamReaderMetrics",
    "StreamReaderState",
    # portable_export
    "AgentOwnershipPortableExportAndNoLockInSuite",
    "ContextArtifactKind",
    "ExportIntegrityReceipt",
    "ExportScope",
    "PortableBundleBuilder",
    "PortableContextBundle",
    "PortableContextItem",
    # topic_drift_fork
    "DriftSignalKind",
    "ForkExecutionResult",
    "SessionForkManager",
    "SessionForkSuggestion",
    "TopicDriftDemarcationAndAutoRenamedSessionForkSuite",
    "TopicDriftDetector",
    "TopicDriftEvaluation",
    # custom_compaction_directives
    "CompactionDirectivesInjector",
    "CompactionIntegrityReport",
    "CustomCompactionConfig",
    "CustomCompactionDirectivesAndPreservationWhitelistSuite",
    "DirectiveAuditResult",
    "PreservationDirective",
    "PreservationDirectiveKind",
    "PreservationWhitelistAuditor",
    # zero_thinking_route
    "DeterministicTaskDetection",
    "DeterministicTaskDetector",
    "ModelProviderKind",
    "ProviderThinkingPayload",
    "ThinkingBudgetMode",
    "ThinkingParameterNormalizer",
    "ZeroThinkingBudgetDirectRouteSuite",
    "ZeroThinkingSavingsRecord",
    # cold_start_profiler
    "ColdStartContextProfile",
    "ColdStartContextProfilerAndOnDemandMcpMountSuite",
    "ColdStartContextProfilerEngine",
    "ContextComponentKind",
    "ContextComponentProfile",
    "McpMountMutationResult",
    "McpServerDescriptor",
    "McpServerMountState",
    "OnDemandMcpMountManager",
    # smart_idle_compactor
    "CacheWindowStatus",
    "CompactedCheckpointArchive",
    "IdleCompactionAction",
    "IdleCompactionEvaluation",
    "IdleCompactorConfig",
    "IdleEligibilityEvaluator",
    "OpportunisticCompactorEngine",
    "OpportunisticCompactionResult",
    "SmartIdleCachePreservingAutoCompactorSuite",
    "ZeroWaitWakeupEvent",
    # command_quiet_rewriter
    "CommandQuietRewriterAndLogSinkSuite",
    "LogSinkConclusionCard",
    "LogSinkStatus",
    "LogSinkTaskSpec",
    "LogSinkTaskType",
    "PreflightCommandRewriter",
    "QuietRewriteRule",
    "RewriteResult",
    "RewriteStatus",
    "SubagentLogSinkEngine",
    "SubagentLogSinkExecutionRecord",
    # cache_shield
    "CacheBreakEvaluation",
    "CacheBreakPreventionShieldEngine",
    "CacheParameterKind",
    "CachePreservingForkResult",
    "CacheRewindResult",
    "CacheRiskLevel",
    "evaluate_parameter_mutation",
    # mention_hydration
    "HydratedTurnPayload",
    "MentionHydrationConfig",
    "MentionHydrationEngine",
    "MentionKind",
    "ParsedMention",
    "PreHydratedAttachment",
    "compute_content_hash",
    "parse_mentions_from_prompt",
    # tool_safe_compaction
    "CutPointEvaluation",
    "CutPointSafetyKind",
    "FileManifests",
    "MessageRole",
    "SafeCompactionResult",
    "ToolSafeCompactionEngine",
    "evaluate_cut_point",
    "extract_file_manifests",
    "find_valid_cut_points",
    "select_optimal_safe_cut_point",
    # browser_batch_script
    "ArtifactFormatKind",
    "BatchExecutionResult",
    "BatchExtractionIntent",
    "BatchFieldSpec",
    "BrowserBatchProcessingEngine",
    "DashboardMetricCard",
    "InteractiveDashboardSpec",
    "PaginationStrategy",
    "SynthesizedBrowserScript",
    "synthesize_batch_crawling_script",
    # branch_projection
    "BranchSummary",
    "DualTrackBranchProjectionEngine",
    "EntryKind",
    "OperationStatus",
    "ProjectedContext",
    "SessionEntry",
    "SessionOperation",
    "TokenUsage",
    "collect_departed_entries",
    "find_lca",
    "synthesize_branch_delta_summary",
    # active_compression
    "ActiveCompressionConfig",
    "ActiveCompressionResult",
    "ActiveContextCompressionEngine",
    "CompressTriggerKind",
    "TokenPressureGauge",
    "TokenPressureLevel",
    "TokenPressureSnapshot",
    # ambiguity_probe
    "AmbiguityClarificationProbe",
    "AmbiguityLevel",
    "BacktrackedContextDossier",
    "ClarificationProbeResult",
    "ClarificationQuestion",
    "EntityGraphMatch",
    # barge_in_steering
    "BargeInMessage",
    "BargeInSteeringConfig",
    "InterventionMode",
    "InterventionStatus",
    "MidRunBargeInSteeringEngine",
    "SteeringPointGateResult",
    # canvas_deeplink
    "CanvasAssetRegistry",
    "CanvasDeepLinkParser",
    "CanvasDeepLinkUri",
    "CanvasDesignAsset",
    "CanvasDesignTokens",
    "CanvasLayerKind",
    "CanvasLayerNode",
    "CanvasTunnelingEngine",
    "ProStudioPlatform",
    "ProStudioSyncPayload",
    # cloud_snapshot
    "CloudSnapshotConfig",
    "IncrementalPatchBundle",
    "InstantCloudSnapshotRestoreEngine",
    "SandboxPoolState",
    "SnapshotRestoreResult",
    "SnapshotStorageDriver",
    "VolumeSnapshotDescriptor",
    "WarmSandboxDescriptor",
    # clean_markdown_extractor
    "CleanMarkdownExtractorConfig",
    "CleanMarkdownExtractorEngine",
    "DOMPruneRule",
    "ExtractedCleanContent",
    "ExtractionDensityLevel",
    "SparsityPruneResult",
    # clean_pod_archival
    "CleanPodArchivalConfig",
    "CleanPodArchivalEngine",
    "EphemeralCleanPodDescriptor",
    "NightlyArchivalJob",
    "NightlyArchivalStatus",
    "PodLifecycleState",
    "TaskDeliverableContract",
    # context_diet
    "ComponentTokenAuditItem",
    "ContextComponentKind",
    "ContextDietBudgetBill",
    "ContextDietConfig",
    "ContextDietEngine",
    "DistilledSkillCard",
    # context_pivot
    "ArchivedContextSnapshot",
    "ContextPivotConfig",
    "ContextPivotResult",
    "HandoffScratchpad",
    "LosslessContextPivotEngine",
    "PivotTriggerKind",
    # demand_hydration
    "DemandHydrationConfig",
    "HydratedContextEnvelope",
    "HydrationDecision",
    "HydrationTriggerMode",
    "OnDemandContextHydrator",
    "ProfileCardCategory",
    "UserMemoryCard",
    # branch_summary
    "BranchFileOperations",
    "BranchFileOperationsTracker",
    "BranchMergeConflictWarning",
    "BranchSelectiveMergeEngine",
    "BranchSummaryResult",
    "FileActionKind",
    "SelectiveMergePolicy",
    "TrackedFileOperation",
    # dual_branching
    "BranchDescriptor",
    "BranchingPosture",
    "DualBranchingSessionEngine",
    "ForkCloneResult",
    "TreeNodeMessage",
    "VersionNavigationInfo",
    # dual_loop_steering
    "DualLoopQueueSnapshot",
    "DualLoopSessionQueueLedger",
    "InnerLoopSteeringInterceptor",
    "KeyStrokeIntent",
    "LoopSteeringKind",
    "SteeringDirective",
    "SteeringDirectiveStatus",
    # dual_track_interjection
    "DualTrackInterventionConfig",
    "DualTrackInterventionCoordinator",
    "InterventionStatus",
    "InterventionTrack",
    "PreemptionQueueSnapshot",
    "StepBoundaryInjectionResult",
    "UserInterventionDirective",
    # emergent_attention
    "ActionTraceEvent",
    "EmergentAttentionDossier",
    "EmergentAttentionEngine",
    "EmergentAttentionItem",
    "InboundNotification",
    "IntentionActionDiffItem",
    "IntentionActionDiffReport",
    "NotificationSieveResult",
    "SieveDecision",
    "StatedIntention",
    "UserActionTraceKind",
    # harness_tax
    "CompactWorkingMemoryProjector",
    "CompactWorkingMemoryView",
    "HarnessTaxAuditReport",
    "HarnessTaxConfig",
    "ResourceLoadBundle",
    "ToolDescriptor",
    "ToolExposurePolicy",
    # hysteresis_compression
    "CooldownStatus",
    "HysteresisCompressionEngine",
    "HysteresisConfig",
    "HysteresisEvaluation",
    "HysteresisExecutionReport",
    "SanctuaryBlock",
    "SanctuaryCategory",
    "WatermarkTier",
    # inbound_shield
    "InboundMessageOverflowShield",
    "InboundMountedDocument",
    "InboundPayloadClassification",
    "InboundShieldConfig",
    "InboundShieldResult",
    # million_token_ceiling
    "CompactionTierAction",
    "CompactionTrackType",
    "ContextBudgetForecast",
    "MillionTokenCeilingConfig",
    "MillionTokenCompactionResult",
    "MillionTokenCeilingGovernor",
    "OffloadedToolArtifact",
    # multibot_governor
    "BotTurnEvent",
    "CognitiveValueEvaluation",
    "GovernorAction",
    "GovernorDecision",
    "GroupTurnArbitrator",
    "IncrementalCognitiveValueEvaluator",
    "MessageSenderRole",
    "MultiBotChatterGovernor",
    "MultiBotGovernorConfig",
    "MutexAcquireResult",
    # owner_fencing
    "AdmissionDecision",
    "AdmissionStatus",
    "DurableSessionOwnerFencer",
    "FencingConfig",
    "SessionOwnerLease",
    "SessionQuiesceState",
    # privacy_mode
    "ConversationPrivacyGateEngine",
    "PrivacyBoundToolSet",
    "PrivacyModeLevel",
    "PrivacyModeSessionConfig",
    "ToolCallInterceptRecord",
    "ToolHardGateAction",
    # proactive_recall
    "ContextGapAutoProbeEngine",
    "ContextGapDetection",
    "EntityType",
    "PrunedEntityRecord",
    "ProactiveRecallNudgeConfig",
    "ProactiveRecallProbeResult",
    # project_container
    "DragDropIngestionEvent",
    "ProjectAssetItem",
    "ProjectAssetKind",
    "ProjectContainerWorkspace",
    "SessionVisibilityStatus",
    "SilentArchivingResult",
    "UnifiedProjectContainerEngine",
    # rule_lifecycle
    "AgentRuleLifecycleAuditor",
    "RuleAuditItem",
    "RuleConflictPair",
    "RuleConflictType",
    "RuleLifecycleConfig",
    "RuleLifecycleReport",
    "RuleLifecycleState",
    # session_commit
    "CommitJobStatus",
    "CommitTriggerReason",
    "ExperienceLearningItem",
    "Phase1SnapshotResult",
    "ProjectGuidelineItem",
    "SessionCommitJob",
    "SessionCommitPolicyConfig",
    "TriDimensionalDistillationResult",
    "TwoPhaseSessionCommitEngine",
    "UserPreferenceItem",
    # session_dom
    "RewindLifecycleAction",
    "RewindLifecycleWorklist",
    "SessionDomNode",
    "SessionDomNodeKind",
    "SessionDomPatch",
    "SessionDomPatchOp",
    "SessionDomTree",
    "UniversalEventSourcedSessionDomEngine",
    # session_bridge
    "BridgeMessageItem",
    "ExportBridgeResult",
    "ExternalHarnessFormat",
    "FullStateHandoffBundle",
    "SessionWorkspaceState",
    "ToolExecutionTrace",
    "UniversalSessionBridgeEngine",
    "UniversalSessionDescriptor",
    # skill_immunity
    "ActiveSkillImmunityEngine",
    "ActiveSkillSpec",
    "ReAnchorAnchorPosition",
    "ReAnchorOutcome",
    "SkillImmunityConfig",
    "SkillImmunityScope",
    # mvp_distiller
    "ComplexProjectMvpDistillerEngine",
    "DistillationOutcome",
    "ModuleSpec",
    "MvpDistillerConfig",
    "MvpPhaseLifecycleState",
    "PhaseScopePlan",
    "ProjectComplexityLevel",
    # cron_mirroring
    "ContinuableCronSessionMirrorEngine",
    "ContinuableJobSpec",
    "CronDeliveryRecord",
    "CronMirrorConfig",
    "CronMirrorRoleMode",
    "CronMirroringOutcome",
    # ipc_clamping
    "IpcClampingAction",
    "IpcClampingConfig",
    "IpcClampingOutcome",
    "IpcMessageClampingAndSpilloverEngine",
    "SpilloverArtifactSpec",
    # dual_file_decoupling
    "DualFileContextEnvelope",
    "DualFileDecouplingConfig",
    "DualFileProjectContextDecouplingEngine",
    "DynamicOverviewSections",
    "ProjectRuleInvariantSpec",
    # project_handoff
    "HandoffHandshakeResponse",
    "ProjectHandoffConfig",
    "ProjectHandoffStatus",
    "ProjectWorkspaceDossier",
    "TenSecondProjectHandoffEngine",
    # live_steering
    "LiveResponseSteeringEngine",
    "LiveSteerStatus",
    "LiveSteeringConfig",
    "LiveSteeringInjectionResult",
    "LiveSteeringInstruction",
    "LiveSteeringReconciledHistory",
    "SteerChannelMode",
    "SteerSeverity",
    "ToolSeamAnchor",
    # token_governor
    "BurnRateTelemetry",
    "BurnRateZone",
    "LeanToolPruningDecision",
    "RateLimitBackoffDecision",
    "TokenBurnRateGovernorEngine",
    "TokenGovernorConfig",
    "TokenUsageRecord",
    "ToolLeanMode",
    # sandbox_interceptor
    "ContextHookStage",
    "InterceptedToolOutput",
    "LifecycleHookRecord",
    "SandboxInterceptorConfig",
    "SandboxOutputInterceptorEngine",
    "SearchResultSnippet",
    "ToolOutputStub",
    # sandbox_reduction
    "ActionKind",
    "ActionLedgerEntry",
    "InSandboxDataReductionEngine",
    "LedgerQueryResult",
    "ReducedOutputEnvelope",
    "ReductionKind",
    "SandboxReductionConfig",
    # sandplay_simulation
    "CausalityEdge",
    "CausalityNode",
    "CausalityTier",
    "FinancialSandplaySimulationEngine",
    "ImpactDirection",
    "IndustryChainGraph",
    "SandplaySimulationResult",
    "SolidifiedSkillPackage",
    # prompt_cache_clock
    "CacheTierKind",
    "ClockBucketResolution",
    "ContextClockSpec",
    "PromptCacheClockConfig",
    "PromptCacheClockGovernorEngine",
    "PromptCacheTierBlock",
    "TieredAssemblyResult",
    "ToolChoiceMode",
    # fallback_buffer_notebook
    "BufferWatermarkSnapshot",
    "BufferWatermarkState",
    "CompactionConsequenceAlert",
    "FallbackBufferConfig",
    "FallbackBufferNotebookEngine",
    "TeamNotebookEntry",
    "TeamNotebookSnapshot",
    # migratable_session
    "DecoupledMigratableSessionEngine",
    "MigratableSessionBundle",
    "MigratableSessionConfig",
    "SessionAccessRole",
    "SessionForkOutcome",
    "SessionLiveStatus",
    "SessionLocationKind",
    "SessionShareGrant",
    "WorkspaceHotSeedSpec",
    # session_antidote
    "AntidoteReceipt",
    "ConfigDriftDetail",
    "ConfigMutationProposal",
    "FlagScope",
    "GenesisConfigSnapshot",
    "PoisonDiagnosisReport",
    "PoisonSeverity",
    "SessionAntiPoisoningEngine",
    "SessionAntidoteConfig",
    # reasoning_collapse
    "ReasoningCollapseConfig",
    "ReasoningCollapseReport",
    "ReasoningStreamCollapseEngine",
    "ReasoningVendorType",
    "ThinkingCollapseMode",
    "UnifiedReasoningBlock",
    # progressive_disclosure
    "AttributionValidationResult",
    "CognitiveMilestoneFact",
    "DisclosureStage",
    "EvidenceAttributionType",
    "EvidenceCitation",
    "ProgressiveDisclosureConfig",
    "ProgressiveDisclosureEngine",
    # tool_paging
    "ModelNativeToolPagingEngine",
    "ModelTier",
    "PageInSlice",
    "ToolBlobRecord",
    "ToolOutputStub",
    "ToolPagingConfig",
    "ToolSchemaDefinition",
    # token_efficiency
    "NegativeRouteDecision",
    "NegativeRouteRule",
    "ProviderUsageAnchor",
    "ReasoningSealBlock",
    "TokenEfficiencyConfig",
    "TokenEfficiencyGovernorEngine",
    "TokenEfficiencyLedger",
    # session_roaming
    "CollaborationRole",
    "DeviceAgnosticSessionRoamingEngine",
    "DevicePlatform",
    "ExecutableTeamShareBundle",
    "ForkAndContinueResult",
    "SandboxWarmMirrorSpec",
    "SessionRoamingBreakpoint",
    # shareable_fork
    "InteractiveShareableForkEngine",
    "LosslessForkResult",
    "ShareAccessPermission",
    "ShareTokenPayload",
    "ShareableForkConfig",
    "SharedSessionPerspective",
    # worktree_isolation
    "SessionWorktreeBinding",
    "WorktreeDescriptor",
    "WorktreeHygieneReport",
    "WorktreeHygieneStatus",
    "WorktreeRemovalPolicy",
    "WorktreeRemovalResult",
    # workspace_guard
    "ExplorationDecisionStatus",
    "ExplorationGuardDecision",
    "PromptCrawlSuppressionFilter",
    "WorkspaceAccessPolicy",
    "WorkspaceExplorationGuardEngine",
    "WorkspaceGuardConfig",
    # subagent_scratchpad
    "EphemeralSubagentDossier",
    "FactCategory",
    "MultiAgentSharedScratchpadEngine",
    "ScratchpadQueryFilter",
    "SharedScratchpadFact",
    "SubagentLifecycleStatus",
    # visual_pruner
    "PrunedFrameFootprint",
    "VisualFramePruningEngine",
    "VisualPruningConfig",
    "VisualPruningMode",
    "VisualPruningResult",
    # desktop_repl
    "DesktopApiSdk",
    "DesktopElementMock",
    "DesktopReplSessionSnapshot",
    "PersistentDesktopReplEngine",
    "ReplExecutionResult",
    "ReplExecutionStatus",
    "ReplRuntimeKind",
    "ReplScriptCommand",
    # turn_truncation
    "CanonicalTurnCommit",
    "IntermediateTrialKind",
    "PrefixCacheStabilityReport",
    "TrialStepRecord",
    "TruncationPolicy",
    "TurnExecutionState",
    "TurnStateTruncationEngine",
    # revocation_eviction
    "RevocationDirective",
    "RevocationEvictionEngine",
    "RevocationScopeKind",
    "SanitizationOutcome",
    "TaintedContentBlock",
    # midflight_steering
    "MidFlightDirective",
    "MidFlightSteeringCoordinator",
    "SteeringDirectiveStatus",
    "SteeringExecutionTelemetry",
    "SteeringInjectionEnvelope",
    "SteeringIntentKind",
    # session_search
    "SearchRoleFilter",
    "SessionHistoryFTS5SearchEngine",
    "SessionSearchHit",
    "SessionSearchQuery",
    "SessionSearchResult",
    "SessionSearchScope",
    # schemas
    "BUILTIN_PROTECTED_TOOLS",
    "COMPACT_RULES",
    "DEFAULT_BUSINESS_PROTECTED_TOOLS",
    "DEFAULT_CONTEXT_CONFIG",
    "DEFAULT_SOFT_ONLY_TOOLS",
    # filter
    "FILTER_TOKEN_THRESHOLD",
    "SEMANTIC_CONTENT_TYPES",
    "STRUCTURAL_CONTENT_TYPES",
    "TOOL_PROTECTION_CONFIG",
    # context
    "AgentContext",
    "ArchiveRestoreBlockEvent",
    # artifact_tracker
    "ArtifactAction",
    "ArtifactRecord",
    "ArtifactTracker",
    # filters
    "BaseFilter",
    "BaseProcessor",
    "CacheTtlPrunePolicy",
    "CacheUsageFeedback",
    "CompactToolCall",
    "CompressProcessor",
    "CompressionEvent",
    "CompressionIntent",
    "ContextArchiveReference",
    "ContextCompressOffloadCallback",
    "ContextConfig",
    "ContextOffloadResult",
    # pipeline
    "ContextPipeline",
    "ContextSnapshotCallback",
    "ExplicitCacheProcessor",
    "FilterContext",
    "FilterProcessor",
    "FilterResult",
    "FilteredResult",
    "LocalWorkingMemoryBlock",
    "LocalWorkingState",
    "ProcessorContext",
    "ReasoningAnchorProcessor",
    "RefetchEvent",
    "SemanticFilter",
    "SessionNotesProcessor",
    "StructuralFilter",
    "StructuredSummary",
    "SubtaskItem",
    "SubtaskStatus",
    "SummarizeProcessor",
    # task_metrics
    "TaskMetrics",
    "ThinkingBlockCleaner",
    "ToolProtectionConfig",
    "ToolPruneMode",
    "TrapRecord",
    "acquire_context_lock",
    "build_default_processors",
    "clear_all_locks",
    "clear_artifact_tracker",
    "clear_task_metrics",
    "compress_messages_async",
    "compress_tool_message_async",
    "create_artifact_tracker",
    "create_default_pipeline",
    "create_filtered_result",
    "create_task_metrics",
    "detect_content_type",
    "format_filtered_message",
    "generate_structured_summary",
    "get_active_session_count",
    "get_all_active_metrics",
    "get_all_active_trackers",
    "get_artifact_tracker",
    "get_current_chat_id",
    "get_locked_session_count",
    "get_or_create_artifact_tracker",
    "get_or_create_task_metrics",
    # session_lock
    "get_session_lock",
    "get_task_metrics",
    "record_archive_refetch_for_path",
    "reset_current_chat_id",
    "resolve_cache_ttl_prune_policy",
    "set_current_chat_id",
    # filter
    "should_filter",
    # summarizer
    "should_summarize",
]
