"""Data models for document attachment lifecycle and ownership management."""

from dataclasses import dataclass, field
from time import time


@dataclass(frozen=True)
class AttachmentOwnershipItem:
    """Represents an attachment metadata record strongly owned by a single document.

    Composite identity is scoped to document_id and attachment_id.
    """

    attachment_id: str
    document_id: str
    attachment_hash: str
    storage_key: str
    file_name: str
    mime_type: str
    byte_size: int
    created_at: float = field(default_factory=time)


@dataclass
class StorageBlobMetadata:
    """Tracks physical storage blob references and lifecycle."""

    storage_key: str
    attachment_hash: str
    byte_size: int
    ref_count: int = 1
    physical_path: str | None = None
    last_accessed_at: float = field(default_factory=time)

    def increment(self) -> int:
        """Increment reference count and update access timestamp."""
        self.ref_count += 1
        self.last_accessed_at = time()
        return self.ref_count

    def decrement(self) -> int:
        """Decrement reference count and update access timestamp."""
        self.ref_count = max(0, self.ref_count - 1)
        self.last_accessed_at = time()
        return self.ref_count


@dataclass(frozen=True)
class ReclaimAuditReport:
    """Report generated by deterministic garbage collection sweeps."""

    scanned_blobs: int
    reclaimed_blobs: int
    freed_bytes: int
    retained_blobs: int
    reclaimed_storage_keys: tuple[str, ...]
    elapsed_ms: float


@dataclass(frozen=True)
class MigrationLegacyEntry:
    """Represents a legacy unflattened attachment or relation record."""

    legacy_id: str
    attachment_hash: str
    file_name: str
    mime_type: str
    byte_size: int
    associated_document_ids: tuple[str, ...]


@dataclass(frozen=True)
class MigrationReport:
    """Audit report produced when migrating legacy attachments to document ownership."""

    total_scanned: int
    migrated_records: int
    dropped_orphans: int
    elapsed_ms: float


@dataclass(frozen=True)
class AttachmentStats:
    """Overall attachment and storage health statistics."""

    total_documents: int
    total_attachment_rows: int
    total_storage_keys: int
    total_physical_bytes: int
    orphaned_unclaimed_keys: int
