#!/usr/bin/env python3
"""Repair Next.js lane residue in the shared TypeScript config files.

Two files are shared by every isolated dev lane and each needs a different remedy:

``tsconfig.json`` is now *structurally* immune. Next only skips its config rewrite
when the config declares ``extends``/``references``, which this project does, so a
lane can no longer inject its dist into the committed include list. The check is
kept as a safety net for configs that predate that split.

``next-env.d.ts`` has no such escape hatch: Next rewrites it unconditionally from the
active ``distDir`` without ever consulting the tsconfig. A lane that exits while a
peer lane is still running therefore leaves the shared file naming a dist that the
reaper then deletes, and ``tsc`` fails with
``TS2882: Cannot find module ... side-effect import of './.next-isolated-...'``.
The fix is to reset the file to the canonical ``.next`` dist, which Next regenerates
on its next verify.

The E2E reaper and the stack-startup hygiene pass both call this script.

Run after E2E teardown or ``bun run cleanup``::

    python3 scripts/strip_isolated_tsconfig.py
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

_NEXT_ENV_DIST_DIR = ".next"


def _next_env_text(dist_dir: str) -> str:
    """Canonical next-env.d.ts body for ``dist_dir``, mirroring Next's own writer.

    Next rewrites this file from scratch on every TypeScript verify, so the repair
    target must match what Next emits for the canonical dist: references plus the
    ``routes``/``root-params`` imports. The extra ``cache-life``/``validator``/``link``
    imports only appear under ``strictRouteTypes``/``typedRoutes``, which this project
    does not enable.
    """
    return (
        '/// <reference types="next" />\n'
        '/// <reference types="next/image-types/global" />\n'
        f'import "./{dist_dir}/dev/types/routes.d.ts";\n'
        f'import "./{dist_dir}/dev/types/root-params.d.ts";\n'
        "\n"
        "// NOTE: This file should not be edited\n"
        "// see https://nextjs.org/docs/app/api-reference/config/typescript for more information.\n"
    )


def strip_tsconfig(frontend_root: Path) -> list[str]:
    tsconfig_path = frontend_root / "tsconfig.json"
    if not tsconfig_path.is_file():
        return ["tsconfig.json missing"]

    data = json.loads(tsconfig_path.read_text(encoding="utf-8"))
    include = data.get("include", [])
    if not isinstance(include, list):
        return []

    removed: list[str] = []
    cleaned: list[str] = []
    for entry in include:
        if isinstance(entry, str) and ".next-isolated-" in entry:
            removed.append(entry)
            continue
        if isinstance(entry, str):
            cleaned.append(entry)

    if not removed:
        return []

    data["include"] = cleaned
    tsconfig_path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return removed


def strip_next_env(frontend_root: Path) -> bool:
    """Repair next-env.d.ts when it references a non-canonical dist directory.

    Next rewrites this file unconditionally from the active ``distDir``, and it never
    consults ``tsconfig.json`` — so unlike the config itself it has no ``extends``
    escape hatch. Every isolated lane therefore leaves its own dist behind:

    * a lane that exited while a peer lane was still running keeps its dist path in
      this shared file even after the reaper deleted that dist directory, so the
      project references type files that no longer exist;
    * the canonical dist is ``.next`` (``next.config.ts`` only overrides ``distDir``
      when ``MYRM_NEXT_DIST_DIR`` is set), so any other dist in this file is lane
      residue by definition.

    Rewriting to the canonical text is safe because the referenced type files are
    regenerated by Next on the next verify; a file already naming ``.next`` is left
    untouched so this stays idempotent.
    """
    next_env_path = frontend_root / "next-env.d.ts"
    if not next_env_path.is_file():
        return False

    content = next_env_path.read_text(encoding="utf-8")
    referenced = re.findall(r'^\s*import\s+"\./([^"]+)"', content, flags=re.MULTILINE)
    canonical_prefix = f"{_NEXT_ENV_DIST_DIR}/"
    if all(ref.startswith(canonical_prefix) for ref in referenced):
        return False

    canonical = _next_env_text(_NEXT_ENV_DIST_DIR)
    if content == canonical:
        return False
    next_env_path.write_text(canonical, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--frontend-root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
    )
    args = parser.parse_args(argv)

    frontend_root: Path = args.frontend_root.resolve()
    removed = strip_tsconfig(frontend_root)
    env_fixed = strip_next_env(frontend_root)

    if removed:
        for entry in removed:
            print(f"Removed tsconfig include: {entry}")
    if env_fixed:
        print("Reset next-env.d.ts to .next/dev/types reference")

    if not removed and not env_fixed:
        print("OK (no isolated tsconfig pollution)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
