import type { ThemeProfileRecipe } from './schema';

const BASE_ART = {
  focusX: 0.5,
  focusY: 0.42,
  wash: 0.46,
  mediaKind: 'none' as const,
  assetRef: null,
  posterAssetRef: null,
};

export const OFFICIAL_DEFAULT_PROFILE_ID = 'official-default';

export const BUILTIN_THEME_PROFILES: ThemeProfileRecipe[] = [
  {
    id: OFFICIAL_DEFAULT_PROFILE_ID,
    name: 'Official Default',
    layoutId: 'full-bleed',
    fontId: 'inter',
    builtin: true,
    palette: {
      primaryLight: '#588e95',
      primaryDark: '#6ba3aa',
      primaryHoverLight: '#4a7d84',
      primaryHoverDark: '#7eb5bc',
      primaryDarkLight: '#10505a',
      primaryDarkDark: '#588e95',
      accentWarmLight: '#e07830',
      accentWarmDark: '#f5b868',
      dualAccent: true,
    },
    art: { ...BASE_ART },
  },
  {
    id: 'preset-teal',
    name: 'Teal',
    layoutId: 'nav-rail-focus',
    fontId: 'inter',
    builtin: true,
    palette: {
      primaryLight: '#588e95',
      primaryDark: '#6ba3aa',
      primaryHoverLight: '#4a7d84',
      primaryHoverDark: '#7eb5bc',
      primaryDarkLight: '#10505a',
      primaryDarkDark: '#588e95',
      dualAccent: false,
    },
    art: { ...BASE_ART },
  },
  {
    id: 'preset-rose',
    name: 'Rose',
    layoutId: 'chat-hero',
    fontId: 'inter',
    builtin: true,
    palette: {
      primaryLight: '#c4567a',
      primaryDark: '#f472b6',
      primaryHoverLight: '#a8425f',
      primaryHoverDark: '#ec4899',
      primaryDarkLight: '#8c3050',
      primaryDarkDark: '#db2777',
      dualAccent: false,
    },
    art: { ...BASE_ART },
  },
  {
    id: 'preset-amber',
    name: 'Amber',
    layoutId: 'full-bleed',
    fontId: 'inter',
    builtin: true,
    palette: {
      primaryLight: '#b4762c',
      primaryDark: '#fbbf24',
      primaryHoverLight: '#996320',
      primaryHoverDark: '#f59e0b',
      primaryDarkLight: '#7d5018',
      primaryDarkDark: '#d97706',
      dualAccent: false,
    },
    art: { ...BASE_ART },
  },
  {
    id: 'preset-violet',
    name: 'Violet',
    layoutId: 'nav-rail-focus',
    fontId: 'inter',
    builtin: true,
    palette: {
      primaryLight: '#7c4dba',
      primaryDark: '#a78bfa',
      primaryHoverLight: '#6b3fa4',
      primaryHoverDark: '#8b5cf6',
      primaryDarkLight: '#5a338e',
      primaryDarkDark: '#7c3aed',
      dualAccent: false,
    },
    art: { ...BASE_ART },
  },
  {
    id: 'preset-ocean',
    name: 'Ocean',
    layoutId: 'chat-hero',
    fontId: 'inter',
    builtin: true,
    palette: {
      primaryLight: '#2563eb',
      primaryDark: '#60a5fa',
      primaryHoverLight: '#1d4ed8',
      primaryHoverDark: '#3b82f6',
      primaryDarkLight: '#1e40af',
      primaryDarkDark: '#2563eb',
      dualAccent: false,
    },
    art: { ...BASE_ART },
  },
  {
    id: 'preset-atkinson-calm',
    name: 'Calm Readable',
    layoutId: 'work-dense',
    fontId: 'atkinson',
    builtin: true,
    palette: {
      primaryLight: '#4a7d84',
      primaryDark: '#6ba3aa',
      primaryHoverLight: '#3d6b72',
      primaryHoverDark: '#7eb5bc',
      primaryDarkLight: '#2f555b',
      primaryDarkDark: '#588e95',
      dualAccent: false,
    },
    art: { ...BASE_ART, wash: 0.58 },
  },
  {
    id: 'preset-dark-comfort',
    name: 'Dark Comfort',
    layoutId: 'nav-rail-focus',
    fontId: 'atkinson',
    builtin: true,
    palette: {
      primaryLight: '#7a9a8e',
      primaryDark: '#8fb8a8',
      primaryHoverLight: '#6a8a7e',
      primaryHoverDark: '#a0c8b8',
      primaryDarkLight: '#4a6a5e',
      primaryDarkDark: '#7a9a8e',
      dualAccent: false,
    },
    art: { ...BASE_ART, wash: 0.55 },
  },
  {
    id: 'preset-paper-sepia',
    name: 'Paper Sepia',
    layoutId: 'full-bleed',
    fontId: 'atkinson',
    builtin: true,
    palette: {
      primaryLight: '#8b7355',
      primaryDark: '#b8a080',
      primaryHoverLight: '#7a6248',
      primaryHoverDark: '#c8b090',
      primaryDarkLight: '#5c4a38',
      primaryDarkDark: '#8b7355',
      dualAccent: false,
    },
    art: { ...BASE_ART, wash: 0.52 },
  },
  {
    id: 'preset-moss',
    name: 'Moss Green',
    layoutId: 'chat-hero',
    fontId: 'inter',
    builtin: true,
    palette: {
      primaryLight: '#5a7a5e',
      primaryDark: '#7da882',
      primaryHoverLight: '#4a6a4e',
      primaryHoverDark: '#8db892',
      primaryDarkLight: '#3a5a3e',
      primaryDarkDark: '#5a7a5e',
      dualAccent: false,
    },
    art: { ...BASE_ART },
  },
  {
    id: 'preset-sunset',
    name: 'Sunset',
    layoutId: 'full-bleed',
    fontId: 'inter',
    builtin: true,
    palette: {
      primaryLight: '#c06030',
      primaryDark: '#e8884a',
      primaryHoverLight: '#a85028',
      primaryHoverDark: '#f0985a',
      primaryDarkLight: '#8a4020',
      primaryDarkDark: '#c06030',
      dualAccent: false,
    },
    art: { ...BASE_ART },
  },
  {
    id: 'preset-midnight',
    name: 'Midnight',
    layoutId: 'nav-rail-focus',
    fontId: 'system',
    builtin: true,
    palette: {
      primaryLight: '#4a6a9a',
      primaryDark: '#6a8aba',
      primaryHoverLight: '#3a5a8a',
      primaryHoverDark: '#7a9aca',
      primaryDarkLight: '#2a4a7a',
      primaryDarkDark: '#4a6a9a',
      dualAccent: false,
    },
    art: { ...BASE_ART },
  },
  {
    id: 'preset-terminal',
    name: 'Terminal',
    layoutId: 'work-dense',
    fontId: 'system',
    builtin: true,
    palette: {
      primaryLight: '#2a9a48',
      primaryDark: '#40d868',
      primaryHoverLight: '#208838',
      primaryHoverDark: '#50e878',
      primaryDarkLight: '#187828',
      primaryDarkDark: '#2a9a48',
      dualAccent: false,
    },
    art: { ...BASE_ART },
  },
  {
    id: 'preset-studio-gray',
    name: 'Studio Gray',
    layoutId: 'nav-rail-focus',
    fontId: 'inter',
    builtin: true,
    palette: {
      primaryLight: '#6a6a72',
      primaryDark: '#8a8a92',
      primaryHoverLight: '#5a5a62',
      primaryHoverDark: '#9a9aa2',
      primaryDarkLight: '#4a4a52',
      primaryDarkDark: '#6a6a72',
      dualAccent: false,
    },
    art: { ...BASE_ART },
  },
  {
    id: 'preset-peach',
    name: 'Peach Blush',
    layoutId: 'chat-hero',
    fontId: 'inter',
    builtin: true,
    palette: {
      primaryLight: '#c87060',
      primaryDark: '#e89888',
      primaryHoverLight: '#b86050',
      primaryHoverDark: '#f0a898',
      primaryDarkLight: '#a05040',
      primaryDarkDark: '#c87060',
      dualAccent: false,
    },
    art: { ...BASE_ART },
  },
  {
    id: 'preset-cream',
    name: 'Cream',
    layoutId: 'full-bleed',
    fontId: 'system',
    builtin: true,
    palette: {
      primaryLight: '#a08860',
      primaryDark: '#c8b080',
      primaryHoverLight: '#907850',
      primaryHoverDark: '#d8c090',
      primaryDarkLight: '#706040',
      primaryDarkDark: '#a08860',
      dualAccent: false,
    },
    art: { ...BASE_ART },
  },
  {
    id: 'preset-mint',
    name: 'Mint Fresh',
    layoutId: 'nav-rail-focus',
    fontId: 'inter',
    builtin: true,
    palette: {
      primaryLight: '#3a9a8a',
      primaryDark: '#58c0b0',
      primaryHoverLight: '#2a8a7a',
      primaryHoverDark: '#68d0c0',
      primaryDarkLight: '#207a6a',
      primaryDarkDark: '#3a9a8a',
      dualAccent: false,
    },
    art: { ...BASE_ART },
  },
];

export function getBuiltinProfile(id: string): ThemeProfileRecipe | undefined {
  return BUILTIN_THEME_PROFILES.find((profile) => profile.id === id);
}

export function getDefaultThemeProfile(): ThemeProfileRecipe {
  return BUILTIN_THEME_PROFILES[0];
}
