"""Channel system domain types — pure data definitions, no I/O.

Re-exports all public symbols so callers can use a single import:
    from ...channels.types import OutboundMessage, SessionKey, ...
"""

from .components import (
    ActionButton,
    ButtonStyle,
    ComponentRow,
    QuickReply,
    SelectMenu,
    SelectOption,
    ToolStep,
    render_components_as_text,
    render_quick_replies_as_text,
)
from .messages import (
    ContextEntry,
    CorrelationContext,
    CronContext,
    InboundMessage,
    MediaAttachment,
    MediaType,
    MessagePriority,
    OutboundMessage,
    ProgressUpdate,
    ReasoningDisplay,
    RenderStyle,
    ReplyContext,
    StreamingText,
    STTResult,
    ToolSummaryDisplay,
    TopicContext,
    TTSMode,
    VoiceConfig,
    extract_cron_context,
    guess_media_type,
)
from .notification import (
    METADATA_EXPLICIT_MENTION_KEY,
    METADATA_GUEST_TURN_KEY,
    METADATA_NOTIFY_KEY,
    ChannelNotificationMode,
    parse_notification_mode,
)
from .session import (
    SessionKey,
    SessionPolicy,
    SessionResetMode,
    compute_daily_epoch,
)
from .status import (
    ChannelActivity,
    ChannelCapabilities,
    ChannelHealth,
    ChannelIssue,
    ChannelStatus,
    GroupInfo,
    IssueKind,
    IssueSeverity,
    ReactionLevel,
    StartMode,
)
from .thread_sharing import ThreadSharingMode

__all__ = [
    "METADATA_EXPLICIT_MENTION_KEY",
    "METADATA_GUEST_TURN_KEY",
    "METADATA_NOTIFY_KEY",
    "ActionButton",
    "ButtonStyle",
    "ChannelActivity",
    "ChannelCapabilities",
    "ChannelHealth",
    "ChannelIssue",
    "ChannelNotificationMode",
    "ChannelStatus",
    "ComponentRow",
    "ContextEntry",
    "CorrelationContext",
    "CronContext",
    "GroupInfo",
    "InboundMessage",
    "IssueKind",
    "IssueSeverity",
    "MediaAttachment",
    "MediaType",
    "MessagePriority",
    "OutboundMessage",
    "ProgressUpdate",
    "QuickReply",
    "ReactionLevel",
    "ReasoningDisplay",
    "RenderStyle",
    "ReplyContext",
    "STTResult",
    "SelectMenu",
    "SelectOption",
    "SessionKey",
    "SessionPolicy",
    "SessionResetMode",
    "StartMode",
    "StreamingText",
    "TTSMode",
    "ThreadSharingMode",
    "ToolStep",
    "ToolSummaryDisplay",
    "TopicContext",
    "VoiceConfig",
    "compute_daily_epoch",
    "extract_cron_context",
    "guess_media_type",
    "parse_notification_mode",
    "render_components_as_text",
    "render_quick_replies_as_text",
    "should_notify",
    "with_final_notify",
]
