"""Lifecycle exports."""

from .browser import (
    cleanup_and_warmup_browser_threads,
    cleanup_browser_threads,
    shutdown_global_browser_pool,
    warmup_browser_sessions,
    warmup_global_browser_pool,
)
from .memory_guardian import start_memory_guardian_scheduler, stop_memory_guardian_scheduler
from .monitors import (
    start_auth_alert_monitor,
    start_health_history_recorder,
    start_maintenance_scheduler,
    start_memory_pressure_monitor,
    stop_auth_alert_monitor,
    stop_health_history_recorder,
    stop_memory_pressure_monitor,
)
from .schedulers import (
    start_approval_ttl_scheduler,
    start_auth_log_cleanup_scheduler,
    start_cancellation_cleanup_scheduler,
    start_context_cleanup_scheduler,
    start_context_compaction_telemetry_dispatcher,
    start_cron_scheduler,
    start_db_maintenance_scheduler,
    start_kanban_dispatchers,
    start_login_session_cleanup_scheduler,
    start_remote_backup_scheduler,
    stop_approval_ttl_scheduler,
    stop_auth_log_cleanup_scheduler,
    stop_cancellation_cleanup_scheduler,
    stop_context_cleanup_scheduler,
    stop_context_compaction_telemetry_dispatcher,
    stop_db_maintenance_scheduler,
    stop_kanban_dispatchers,
    stop_login_session_cleanup_scheduler,
    stop_remote_backup_scheduler,
)
from .skills import shutdown_skill_optimization_listeners, start_skill_optimization_listeners
from .system import (
    init_allowlist_store,
    init_risk_rules,
    pause_orphaned_active_goals,
    resume_durable_offline_tasks,
    start_channel_gateway,
    start_idle_task_listeners,
)

__all__ = [
    "cleanup_and_warmup_browser_threads",
    "cleanup_browser_threads",
    "shutdown_global_browser_pool",
    "warmup_browser_sessions",
    "warmup_global_browser_pool",
    "start_auth_alert_monitor",
    "start_health_history_recorder",
    "start_maintenance_scheduler",
    "start_memory_pressure_monitor",
    "stop_auth_alert_monitor",
    "stop_health_history_recorder",
    "stop_memory_pressure_monitor",
    "start_approval_ttl_scheduler",
    "start_auth_log_cleanup_scheduler",
    "start_cancellation_cleanup_scheduler",
    "start_context_cleanup_scheduler",
    "start_context_compaction_telemetry_dispatcher",
    "start_cron_scheduler",
    "start_db_maintenance_scheduler",
    "start_kanban_dispatchers",
    "start_login_session_cleanup_scheduler",
    "start_remote_backup_scheduler",
    "stop_approval_ttl_scheduler",
    "stop_auth_log_cleanup_scheduler",
    "stop_cancellation_cleanup_scheduler",
    "stop_context_cleanup_scheduler",
    "stop_context_compaction_telemetry_dispatcher",
    "stop_db_maintenance_scheduler",
    "stop_kanban_dispatchers",
    "stop_login_session_cleanup_scheduler",
    "stop_remote_backup_scheduler",
    "start_memory_guardian_scheduler",
    "stop_memory_guardian_scheduler",
    "shutdown_skill_optimization_listeners",
    "start_skill_optimization_listeners",
    "init_allowlist_store",
    "init_risk_rules",
    "pause_orphaned_active_goals",
    "resume_durable_offline_tasks",
    "start_channel_gateway",
    "start_idle_task_listeners",
]
